### ISSUE TITLE
Recreation of Details Page (artf375577)

### ISSUE THREAD

**Issue by Vulnerator** [Vulnerator/Vulnerator#1]
Reintroduce a "Details" report (similar to that found in v4.x).  This should primarily be used for STIG/SCAP findings, as "ACAS Output" has its own tab.

**_Note:_** Migration of issue ```artf375577``` from SoftwareForge

**Comment by amkuchta** [comment]
Prematurely auto-closed via pull request #17

**Comment by amkuchta** [comment]
Actually closed now! :+1:
