### ISSUE TITLE
Incorporate License into Download and "About" Screen

### ISSUE THREAD

**Issue by 46-Michael** [Vulnerator/Vulnerator#104]
# Prerequisites
- [X] I have ensured that I am running the latest release
- [ ] The issue is repeatable
- [X] The issue has not already been reported
 
# Category
- [ ] Bug
- [X] Enhancement
- [ ] Assistance Request

# Description
Although the Github page alludes to it with "SoftwareForge to the public domain" (https://github.com/Vulnerator/Vulnerator/blob/86351675c3c746738ba9f55d28e3217f31f544d0/readme.md), there is no license information in any of the source code. This becomes problematic since organizations will face internal legal hurdles using a product and it's outputs if the licensing information isn't readily apparent.

## Expected Outcome
- [X] N/A (Non-Bug Issue)

Addition of a blanket license file/information or the addition of license headers to each source file (if their license may differ).

**Comment by amkuchta** [comment]
@MichaelM00 I have updated the project to include the license file (MIT) - it should now be visible to all on the home page of the application.  For some reason, it didn't take when I initially created the repository (or I forgot to do it, which is not entirely outside of the realm of possibility).

Thanks for catching this!

**Comment by MichaelM00** [comment]
Sigh,
Silly Legal. 

Would it be possible to add a license reference in the program itself (on the about page).  Something like

![image](https://cloud.githubusercontent.com/assets/7794436/25193252/0f4e7406-24fc-11e7-864d-75bdb0bc2651.png)

**Comment by amkuchta** [comment]
@MichaelM00 Not a problem! I'll re-open and milestone it for v6.2.0

**Comment by amkuchta** [comment]
I'll work this in tandem with #92

**Comment by MichaelM00** [comment]
One last thought, if you are wrapping this up into an installer, the license should also be placed as part of the installer (like the typical EULA you see in installers).

I've seen some legal counsel state that we are unable to proceed with installing software that doesn't present a license since the act of a installation conveys use of the product or something.

The alternative to this approach is to include the license file in the zip directory. That also works.

**Comment by amkuchta** [comment]
@MichaelM00 because Vulnerator does not install, I will include it in the zip directory, allowing users to view it during download.  Additionally, I will embed it as readable text on the "About" page, which should cover the base two different ways.

**Comment by MichaelM00** [comment]
Thanks! Greatly appreciate that. Although this seems trivial, it will really save people alot of time going back and forth with legal (speaking from experience).

**Comment by amkuchta** [comment]
@MichaelM00 Boom! (Also, a sneak peak at some layout changes :wink: 
![embeddedlicense](https://cloud.githubusercontent.com/assets/6255186/25441687/f03827ea-2a70-11e7-8577-8bfd7b46c870.jpg)

**Comment by MichaelM00** [comment]
Thanks!

**Comment by amkuchta** [comment]
@MichaelM00 I'm going to keep this open until it is formally closed in the master branch.  Glad you approve!
