### ISSUE TITLE
Stuck on "Creating Report Template..."

### ISSUE THREAD

**Issue by BradP316** [Vulnerator/Vulnerator#117]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [ ] Enhancement
- [x] Assistance Request

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

## Synopsis
I import my checklists and when I click "Execute", all I get is "Creating Report Template."  I have closed out the program, restarted the computer, etc. but the program gets hung up every time.  I also tried creating a POAM with different checklists and get the same issue.

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

_What did you think was going to happen? (Replace this line)_

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

_What really happened? (Replace this line)_ 

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

_How did you get Vulnerator to do that? (Replace this line)_

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@BradP316 can you please upload the log file (or copy and paste its contents into a comment) for review?  If you feel that it contains sensitive data, please feel free to "scrub" it and send it via encrypted email to alex.kuchta@navy.mil

**Comment by BradP316** [comment]
Alex,

 

Thank you for the response.  I actually figured out the issue.  I was running an older version of the software.  I downloaded the newer version and now it works.  Thanks!

 

Brad

**Comment by amkuchta** [comment]
@BradP316 glad to help!  (Even though I didn't have to do anything :laughing:)
