### ISSUE TITLE
BUG in MainWindowViewModel.cs

### ISSUE THREAD

**Issue by Onloadtech** [Vulnerator/Vulnerator#122]
the case below seems to have some mismatched dictionary settings. I found this while looking through the code.  Not sure if this is the desired logic.

```
                        case "rbDiacap":
                            {
                                configAlter.WriteSettingsToDictionary("rbRmf", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }
                        case "rbRmf":
                            {
                                configAlter.WriteSettingsToDictionary("rbDiacap", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }
                        case "rbPki":
                            {
                                configAlter.WriteSettingsToDictionary("rbNone", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }
                        case "rbNone":
                            {
                                configAlter.WriteSettingsToDictionary("rbPki", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }

                        case "rbHostIdentifier":
                            {
                                configAlter.WriteSettingsToDictionary("rbHostIdentifier", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }
                        case "rbIpIdentifier":
                            {
                                configAlter.WriteSettingsToDictionary("rbIpIdentifier", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }

                        case "revisionThreeRadioButton":
                            {
                                configAlter.WriteSettingsToDictionary("revisionFourRadioButton", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }
                        case "revisionFourRadioButton":
                            {
                                configAlter.WriteSettingsToDictionary("revisionThreeRadioButton", (!bool.Parse(commandParameters.controlValue)).ToString());
                                break;
                            }
```

**Comment by amkuchta** [comment]
@Onloadtech thanks!  I'm actually completely rewriting `MainWindowViewModel` for v6.2.0, as I am separating the ViewModel functionality along with the various views and getting rid of the hacked otgether config file in favor of using built-in settings (wayyyyy easier to use).  This one is all but done, but thanks for taking the time to review the code!

As a side note, would you be interested in become a member of the organization that I can bounce ideas off of?  I can add you to a group that allows me to "ping" people who can provide solid feedback.  It would require you to have two factor authentication turned on for your GitHub Account, but it is easy enough to set up.

**Comment by Onloadtech** [comment]
Im sorry I've been pretty busy I would absolutely be interested in
assisting the organization. Ill setup two factor when I can.

On Jul 6, 2017 9:44 AM, "Alex Kuchta" <notifications@github.com> wrote:

@Onloadtech <https://github.com/onloadtech> thanks! I'm actually completely
rewriting MainWindowViewModel for v6.2.0, as I am separating the ViewModel
functionality along with the various views and getting rid of the hacked
otgether config file in favor of using built-in settings (wayyyyy easier to
use). This one is all but done, but thanks for taking the time to review
the code!

As a side note, would you be interested in become a member of the
organization that I can bounce ideas off of? I can add you to a group that
allows me to "ping" people who can provide solid feedback. It would require
you to have two factor authentication turned on for your GitHub Account,
but it is easy enough to set up.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Vulnerator/Vulnerator/issues/122#issuecomment-313400229>,
or mute the thread
