### ISSUE TITLE
Risk Assessment Report does not contain all CCIs from STIGs/SRGs

### ISSUE THREAD

**Issue by lundquisteb** [Vulnerator/Vulnerator#123]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [x] Bug
- [ ] Enhancement
- [ ] Assistance Request

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

## Synopsis
Vulnerator 6.1.9 does not populate all STIG findings in the RAR which forced me to use Vulnerator 6.1.3 which does not populate all CCIs associated with a STIG/SRG check.

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

Processing of the data should have yielded a complete an accurate report with all pertinent information populated in the associated cells/fields, especially for those STIGs that have multiple CCIs associated with them.

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

Vulnerator 6.1.3 and 6.1.9 do not populate the CCI column with all of the CCIs that are associated with those STIGs that have multiple CCIs. Instead, Vulnerator populated the applicable cell with the last CCI of the STIG that has multiple CCIs associated to it.

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

I simple imported the files into Vulnerator and selected execute.
# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@lundquisteb thanks for the bug report!  Part of v6.2.0 is a completely redesigned database, which allows me to make the data more accurate and pivotable.  I have addressed this concern already, it will just need to be put through some final tests before I push the first alpha release out - hang tight!

**Comment by da7rutrak** [comment]
@amkuchta is the work you're doing on v6.2.0 address the issue described here and in #110?

**Comment by amkuchta** [comment]
CCI Information now parses and associates correctly
