### ISSUE TITLE
[Poll] Vulnerator Report Breakouts & Organization Membership

### ISSUE THREAD

**Issue by amkuchta** [Vulnerator/Vulnerator#125]
This is a two part poll - please feel free to respond to either or both items, as you see fit.

### Vulnerator Reporting
Currently, Vulnerator consolidates all Excel reports into a single workbook.  Given the following options, which is most palatable to you:

1. Continue putting all reports into a single workbook
2. Break the reports into separate books, but allow me to choose the file names for each
3. Break the reports into separate workbooks, but only require me to select a directory in which to place them - the application can name them, so long as the name is meaningful (i.e. "09Aug2017_GroupName_POAM.xlsx")

### Organization Membership
To faclilitate polling in the future, I would like to make better use of the "team" capability in GitHub.  I currently have a handful of "advisors" who I can call on via the @Vulnerator/user-reps tag, but would like to expand the pool of critical thinkers.  If you are interested, please send an email to alex.kuchta@navy.mil, preferably from your *.mil email account or using some sort of digital signature (DoD, ECA, etc.).  Additionally, keep in mind that to be added to the organization, you must have two factor authentication enabled (super easy, but it required you to have your phone on hand any time you log into GitHub from a new location / computer).

Thank you in advance for your responses!

**Comment by brjones3** [comment]
#1 is my preference.  I would rather only have one file per vulnerator run, and it's easy to extract the tabs if needed.

**Comment by CyberSecDef** [comment]
I'm all for #1.  If I need to break it apart, I can.

As for question two.....I can't enable two factor authentication from my NMCI seat.  I wish I could, I just can't from this location.

-----Original Message-----

**Comment by CyberSecDef** [comment]
Can you request more 'static' numbers if you use them all?

-----Original Message-----

**Comment by amkuchta** [comment]
@CyberSecDef There is an option to generate new "recovery codes", as they are officially called; screenshot provided for posterity (and redacted for obvious reasons):

![recoverycodescreenshot](https://user-images.githubusercontent.com/6255186/29176317-7d117590-7db9-11e7-9a34-597d99541a26.jpg)

**Comment by CyberSecDef** [comment]
Ok...as soon as I can be on github with my phone I'll change over.  Will give it a shot.

-----Original Message-----

**Comment by vanerj1996** [comment]
#1, it's easy to remove sheets from excel I don't need

**Comment by amkuchta** [comment]
@CyberSecDef any joy on getting 2FA up and running?
