### ISSUE TITLE
Vulnerator failed to import/process .nessus file with no error logs.

### ISSUE THREAD

**Issue by jlong24** [Vulnerator/Vulnerator#127]
![logs](https://user-images.githubusercontent.com/31549237/29983432-060a7120-8f13-11e7-9b95-251661639a82.jpg)
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [ ] I have ensured that I am running the latest release (Company requires the use of an older version 6.0.5813.19862.
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [ ] Enhancement
- [x] Assistance Request

# Description
I'm required to import our ACAS scans to produce POA&Ms / RAR excel worksheet, however our .nessus we try to import is a little more than 300mb.  I tried checking the logs, but it gives no errors and produces a blank worksheet.  Is there a file size limit, if so I can set up the reports to be broken down.

## Synopsis
Vulnerator unable to process/import .nessus scan.

## Expected Outcome
- [x] N/A (Non-Bug Issue)

_What did you think was going to happen? (Replace this line)_

## Actual Outcome
- [x] N/A (Non-Bug Issue)

_What really happened? (Replace this line)_ 

## Reproduction Steps
- [x] N/A (Non-Bug Issue)

_How did you get Vulnerator to do that? (Replace this line)_

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@jlong24  I apologize for the late response - I have been out on vacation for the past week.  With regards to the version that you are using, there is an issue with parsing larger files.  Prior to v6.1.x, all processing was handled in memory, which can cause a `System.OutOfMemoryException` to be thrown.  The fix would be to either reduce the size of the files being parsed or to update to a later version (preferably the most recent).

May I ask why you are limited to that release?

**Comment by jlong24** [comment]
I also apologize for the late reply.  We only had access to the old Vulnerator due to the fact that they couldn't get it working on standard accounts, which is why they didn't release the latest version out.  Works fine as an administrator, also the latest version was able to process our huge file.  Appreciate the help!
