### ISSUE TITLE
Minor output issues

### ISSUE THREAD

**Issue by ibjohn** [Vulnerator/Vulnerator#130]
# Prerequisites

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category

- [x] Bug
- [ ] Enhancement
- [ ] Assistance Request

# Description
1. Inconsistent CCI number format in RAR tab
2. STIGs checklists that end with "STIG" show up in the Source of Discovery column as STIG STIG.

## Synopsis
1. Some CCI numbers are the normal 123456 format but some are "CCI-"123456. Not a big issue, but it will save me some effort if you fix it since I use it to compare to eMASS output to identify open STIG findings to RFM control dump to list open STIG findings not associated to System's RMF baseline controls.

2. STIGs checklists that end with "STIG" show up in the Source of Discovery column as STIG STIG. Example "Remote Access VPN STIG" shows up as "Remote Access VPN STIG STIG". I say just drop adding "STIG".  

Don't blame me - my parents gave me the OCD jean.

# Attachments

- [ ] Vulnerator Log - does not contain anything helpful
- [x] Screenshots (Optional)
![vissue](https://user-images.githubusercontent.com/25967611/30503964-2ffa9294-9a21-11e7-89df-9a2e3f1ef994.png)
![vissue](https://user-images.githubusercontent.com/25967611/30504385-456dd09e-9a23-11e7-8834-3e8d0ce05bff.png)

- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@ibjohn thanks for the report!  Both of these are being corrected in v6.2.0 (I have spent a lot of time handling out data is placed into the database to ensure proper pivotability [which is a word I just made up, according to spellcheck], data integrity, and presentation consistency.  Hang tight!

**Comment by amkuchta** [comment]
Information now parses correctly
