### ISSUE TITLE
Missing NIST Control and CCI

### ISSUE THREAD

**Issue by JimByrne** [Vulnerator/Vulnerator#131]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [x] Bug
- [ ] Enhancement
- [ ] Assistance Request

# Description
Not all NIST Controls contained in a STIG are being extracted to the excel sheets.  And in some instances neither are the CCIs.  

## Synopsis
After processing the Oracle 12C V1R8 STIG checklist in Vulnerator 6.1.9, items V-61603 and V-61643 are both missing the NIST control (which IS displayed in the STIG Viewer), and item V-61643 is also missing one of the two CCIs (which ARE displayed in the STIG Viewer).

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

Vulnerator should extract all NIST controls and all CCIs from STIG checklist files, including instances where there are more than one control or CCI.

## Actual Outcome
Two NIST controls were totally missing, and one CCI was missing.

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

I imported the Oracle 12C V1R8 STIG checklist in Vulnerator 6.1.9, and EXECUTED the Excel output.

# Attachments

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
Closing, as this is a duplicate of #110 and #123.
