### ISSUE TITLE
Vulnerator Added CCI numbers that are NOT supposed to be there

### ISSUE THREAD

**Issue by JimByrne** [Vulnerator/Vulnerator#133]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [x] Bug
- [ ] Enhancement
- [ ] Assistance Request

# Description
CCI are incorrectly added to Vulnerator 6.1.9 XLSX output file

## Synopsis
We used STIG Viewer 2.5.4 to import the entire ZIP STIG Library file (~24000 items), and then to create a CKL and XLSX output files.  Neither output file showed any CCI numbers for the items associated with the Network Devices STIG V8R20, and examining that STIG by itself in the Viewer and in WordPad confirmed that to be correct.  However, when the CKL output file was then loaded in Vulnerator 6.1.9 the resultant XLSX file showed CCI-002111 being associated with ALL 63 items of the STIG.  Note that this is exactly the OPPOSITE of existing bugs that indicate some CCI numbers are MISSING in Vulnerator output.  

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

Because there are no CCI numbers associated with any items in the Network Devices STIG V8R20 when loaded individually by Vulnerator, we expected the Vulnerator output of the Library file when filtered for just that STIG to also contain no CCI numbers.  

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

Instead, the Vulnerator output of the Library file, when filtered for just that STIG, showed CCI-002111 to be associated with ALL 63 of the items in the STIG

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

See the Synopsis above

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@JimByrne this is *roughly* associated with #123 - long story short, my CCI mapping with regards to vulnerabilities left a lot to be desired in past versions.  v6.2.0 will better "decouple" the data, which makes it easier for me to pull the correct information as needed.  Hang tight, and thanks for the issue report (and for using the application)!

**Comment by ibjohn** [comment]
I know they are not on the POAM tab. Did you look on the RAR tab?

**Comment by amkuchta** [comment]
CCI Mappings now associate correctly
