### ISSUE TITLE
Browser for opening mitigation db file defaults to SDF files only

### ISSUE THREAD

**Issue by jlacadd** [Vulnerator/Vulnerator#136]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [x] Bug
- [ ] Enhancement
- [ ] Assistance Request

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

## Synopsis
When clicking the Browse button for the Database location, the browse window comes up but the file extension filter is set to "SDF Files (*.sdf)", while the database file extension is .sqlite.  You can still type in *.* and hit enter to see the file to open it, but this is definitely a bug that could be easily squashed.

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

The default file extension filter should be *.sqlite

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

The default file extension filter is *.sdf

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

Click Mitigations tab, click the Browse button.

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [x] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)
![capture](https://user-images.githubusercontent.com/32691006/31479134-20d5a292-af50-11e7-8e4e-fb8487be7a93.JPG)

**Comment by amkuchta** [comment]
This one has already been addressed in v6.2.0 (I didn't know it existed, but I made some changes that just happen to fix it) - thank you, and hang tight!
