### ISSUE TITLE
Create new mitigation database functionality appears broken

### ISSUE THREAD

**Issue by jlacadd** [Vulnerator/Vulnerator#137]
# Prerequisites

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category

- [x] Bug
- [ ] Enhancement
- [ ] Assistance Request

# Description

## Synopsis
Creating a new database by clicking on the "Create New" button results in a file picker window (filtering to SDF files) and typing any name in the file name text box and clicking Open results in a "file not found" error.  Unless I'm missing something here...looks like you can't create a new database.

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

Clicking the "Create New" button should result in a file window that allows me to specify a location and type a new filename.  Clicking a Save button would result in a new DB file being created at that location and that should be listed in the "Database Location" textbox above the "Create New" and "Browse" buttons.

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

Unable to create a new database file at all.

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

Click the Mitigations tab and click the "Create New" button.  Try typing in any filename and clicking the Open button.  An error occurs that says Title:  Please select Contact Database file   Text:  "<fullpathtofilename> does not exist.  Verify that the file name is correct."

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [x] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)
![capture](https://user-images.githubusercontent.com/32691006/31479380-c1d5efb6-af51-11e7-9b57-3cf73fe1984f.JPG)

**Comment by amkuchta** [comment]
v6.2.0 now uses a single database for everything, and corrects the "creation" behavior to what it is supposed to do.  thank you!
