### ISSUE TITLE
Unable to process FORTIFY ".fpr" files using Vulnerator

### ISSUE THREAD

**Issue by razorb62** [Vulnerator/Vulnerator#147]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [ ] Enhancement
- [x] Assistance Request

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

Vulnerator fails to process Fortify ".fpr" files, log information provided here.
2018-04-20 08:15:10,766        INFO                                                     0                    Begin processing of 
2018-04-20 08:19:43,004        ERROR                                                    0                    Unable to read "audit.xml".
2018-04-20 08:19:43,148        ERROR                                                    0                    Unable to read FPR Archive.
2018-04-20 08:19:43,150        ERROR                                                    0                    Unable to process FPR file.
2018-04-20 08:19:43,152        ERROR                                                    0                     processing failed; Elapsed time: 00:04:32.3881301

## Synopsis
_Place your description here, please! (Replace this line)_

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

_What did you think was going to happen? (Replace this line)_

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

_What really happened? (Replace this line)_ 

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

_How did you get Vulnerator to do that? (Replace this line)_

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@razorb62 thank you for the issue report!  I believe that this is fixed courtesy of a new processing approach that I took for v6.2.0, but I will double check to make sure!

**Comment by razorb62** [comment]
The Fortify version of the .fpr files that fail to process is 17.20, previous Fortify versions complete processing, however, the Vulnerator tool hangs up on "creating excel report(s)..." and all of the Application Execution buttons are greyed out.

**Comment by mhara42** [comment]
I have the same issue with v18.1. 18.2 will be coming out this Fall. My guess is that whatever changed is being carried forward.

**Comment by RoxxW** [comment]
Verified. Unable to process Micro Focus Fortify v18.1 fpr files with v6x Vulnerator

**Comment by RoxxW** [comment]
Happy to help test this when ready

**Comment by mhara42** [comment]
Ditto

**Comment by RoxxW** [comment]
@amkuchta Any chance of getting an advanced beta copy of 6.2 that fixed this? This is killing my IA colleagues. They are literally copying line for line from a PDF Fortify Report into the POA&M template. I am the Fortify SME here.

**Comment by RoxxW** [comment]
Is there a earlier version that DID work with v18x FPR files that we can go back to until the bug is fixed in the most recent release of Vulnerator?

**Comment by lbarraugh** [comment]
Joining the thread because I'm having the same issue.  Happy to help wherever possible to get a resolution.

**Comment by Michael-Angel-Sec** [comment]
Also seeing this issue.  Any resolution or workaround available?

**Comment by sitezero** [comment]
Also having this issue, as of December 2019, any updates?

**Comment by jfinneyfrock** [comment]
I am also having this issue with version 18.2 FPR files.

**Comment by amkuchta** [comment]
Can anyone provide me with a __*redacted*__ 18.2 FPR file?  Emailing it encrypted to alex.kuchta@navy.mil would be best, if possible

**Comment by RoxxW** [comment]
I can DOD SAFE one later today. 

Sent from my iPhone

Mark Berrier
NAVSEA 04

**Comment by amkuchta** [comment]
Fortify FPR files from 18.2 and 20.x now parse correctly

**Comment by razorb62** [comment]
Which version of Vulnerator has this been fixed on?

________________________________

**Comment by amkuchta** [comment]
@razorb62 it's going to be in the next release, due out in about 2 weeks.  I'm now working this full time again (it got put under my team), and I am putting in nights and weekends, as well.  I put in about 150 hours in two weeks so that I can get something out as soon as possible.

**Comment by razorb62** [comment]
Thank you very much, your efforts are appreciated.

________________________________
