### ISSUE TITLE
Vulnerator fails to export report, ERROR in log Findings database refresh failed

### ISSUE THREAD

**Issue by johndfars** [Vulnerator/Vulnerator#149]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [ ] The issue is repeatable
- [ ] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [ ] Enhancement
- [x] Assistance Request

# Description
I had imported an XCCDF results from a SCAP scan done on a Windows box, was able to create a CKL file, and import to Vulernator without issue, saving a POA&M report. However when I tried it with the next one from an RHEL 6 server, it seemed to drop into a loop and not exits. There was an error indicated to check the log. the log indicated:
- unable to count vuln ...
- unable to create ... XLS
- create XLS failed timeout
- unable to create indexes on Findings database

## Synopsis
Vulnerator fails to export report, ERROR in log Findings database refresh failed

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

I would get an XLS report with POA&M

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

it DID create an XLS that was apparently corrupt, went into a loop & froze, log had errors

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

- import XCCDF (STIG results)
- Execute

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
This was resolved "offline" with @johndfars - the issue was a background instance of Vulnerator running.  closing out the issue as "resolved"
