### ISSUE TITLE
Navy Risk Assessment Report (RAR) for RMF process

### ISSUE THREAD

**Issue by PCGOOD** [Vulnerator/Vulnerator#150]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [ ] I have ensured that I am running the latest release
- [ ] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [x] Enhancement
- [ ] Assistance Request

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

## Synopsis
Is there plans to update the RAR report to meet the new RMF RAR that is being use by the Navy?

## Expected Outcome
- [x] N/A (Non-Bug Issue)

_What did you think was going to happen? (Replace this line)_

## Actual Outcome
- [x] N/A (Non-Bug Issue)

_What really happened? (Replace this line)_ 

## Reproduction Steps
- [x] N/A (Non-Bug Issue)

_How did you get Vulnerator to do that? (Replace this line)_

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

[Navy Risk Assessment Report V2.9.zip](https://github.com/Vulnerator/Vulnerator/files/1984593/Navy.Risk.Assessment.Report.V2.9.zip)

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@PCGOOD I'll work on getting the latest version of the RAR into v6.2.0

**Comment by tbedford2008** [comment]
Man! I am very interested in seeing if you were able to add this feature. I am validating systems and have to  populate RAR's. Any significant progress so far?

**Comment by HuggsN** [comment]
Hello... I wanted to drop a note and let you know that the RAR is no longer a required artifact for Navy eMASS submission. All Risk analysis is now being done within the POA&M template. I noticed that the existing POA&M within Vulnerator is slightly setup differently from the eMASS POA&M template we are now using. Is it possible to get that updated to reflect the current requirement? I've attached it for your reference. I am very interested in the latest 6.2.0 and can't wait to download it once the improvements are made. We use this tool pretty heavily. 
NOTE: I converted the POA&M to pdf for reference. We are not going to be able to use the POA&M from Vulnerator to import directly into eMASS but it does help when we transfer some of this data over to the template. 
[eMASS_POAM_Template.pdf](https://github.com/Vulnerator/Vulnerator/files/3592967/eMASS_POAM_Template.pdf)

**Comment by sagansapien** [comment]
I would 

> Hello... I wanted to drop a note and let you know that the RAR is no longer a required artifact for Navy eMASS submission. All Risk analysis is now being done within the POA&M template. I noticed that the existing POA&M within Vulnerator is slightly setup differently from the eMASS POA&M template we are now using. Is it possible to get that updated to reflect the current requirement? I've attached it for your reference. I am very interested in the latest 6.2.0 and can't wait to download it once the improvements are made. We use this tool pretty heavily.
> NOTE: I converted the POA&M to pdf for reference. We are not going to be able to use the POA&M from Vulnerator to import directly into eMASS but it does help when we transfer some of this data over to the template.
> [eMASS_POAM_Template.pdf](https://github.com/Vulnerator/Vulnerator/files/3592967/eMASS_POAM_Template.pdf)

Seconded. The Vulnerator POA&M cannot be imported directly to eMASS at this time. I would very much appreciate the ability to import my Vulnerator POA&M with minimal refactoring. @amkuchta is this template format issue on your radar for a future release? Thank you kindly.

**Comment by amkuchta** [comment]
Can anyone outside of Navy confirm that the RAR is no longer required?

@sagansapien in response to your question, yes, I am currently working to update to the new template.  However, the changes required are two-fold:

1. I re-arranged the GUI and made it more easily extensible, so I have to "re-wire" how the report creation calls are completed
2. The database is entirely new (and improved!), with a completely different table structure. Because of this, the logic has to be re-worked with respect to how the data is retrieved and organized.  Related to that, the new approach I have taken for mitigation creation and association requires a bit of new logic in the SQL call, as well

**Comment by sagansapien** [comment]
> Can anyone outside of Navy confirm that the RAR is no longer required?
> 
> @sagansapien in response to your question, yes, I am currently working to update to the new template. However, the changes required are two-fold:
> 
> 1. I re-arranged the GUI and made it more easily extensible, so I have to "re-wire" how the report creation calls are completed
> 2. The database is entirely new (and improved!), with a completely different table structure. Because of this, the logic has to be re-worked with respect to how the data is retrieved and organized.  Related to that, the new approach I have taken for mitigation creation and association requires a bit of new logic in the SQL call, as well

Awesome, thank you sir. I appreciate your efforts.
