### ISSUE TITLE
Is Vulnerator on the  Common Criteria list

### ISSUE THREAD

**Issue by TheShadow1935** [Vulnerator/Vulnerator#168]
#### Prerequisites
_Before submitting a new request, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The request has not already been reported

#### Description
_Please provide a description of the feature request here._

#### Associated Issues
_Is the feature request the result of an issue (e.g. a bug or an outdated component?)  Please reference any existing issues in the tracker, as appropriate, using "#[IssueNumber]"._

#### System Information
 - _**OS:**_ [e.g. Windows 10]
 - _**Version:**_ [e.g. v6.1.9]

#### Additional Context
_Add any other context about the problem here, if applicable._

#### Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Examples of applications currently using the feature
- [ ] Screenshots (optional, _**SANITIZED AND EMAILED**_)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by TheShadow1935** [comment]
Looking to use this with other departments within DoD and they want to know if its on the Common Criteria list

**Comment by amkuchta** [comment]
@TheShadow1935 unfortunately, no, it is not - the CC evaluation process comes with a cost, and as an open source project, no funding has been allocated to have the process completed.
