### ISSUE TITLE
Excel output of nessus files from scanner version 8.6 does not parse properly

### ISSUE THREAD

**Issue by jasonbongard** [Vulnerator/Vulnerator#174]
#### Prerequisites
_Before submitting a new issue, please ensure you have completed the following (delete the space in the box and replace it with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported

#### Description
1) Asset overview sheet shows no vulnerability counts.  
2) POAM sheet - Status field reports ongoing for all items including informational plugins, raw severity level is unknown for all items.

#### To Reproduce
_How did you get Vulnerator to do that?_
Vulnerate any nessus file from scanner 8.6.  All appears to run fine, but excel file output is showing bad data.

#### Actual Outcome
_What really happened?_

#### System Information
 - Windows 10 SHB 
 -6.1.9

#### Additional Context
_Works fine for scans generated from scanner versions prior to 8.6

#### Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (optional, _**SANITIZED/REDACTED**_)
- [ ] Vulnerability Files (optional, _**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@jasonbongard is this related to #173 at all?

**Comment by jasonbongard** [comment]
Sorry, it is related to 173 and should be closed. I tried searching but didn’t see the related ticket.


________________________________

**Comment by Mr-Mike** [comment]
Nessus version 8.6.0 includes bug fix,  plugin attributes were no longer included in .nessus files sent to T.sc.

In Nessus 8.6.0 software, under settings, advanced settings, performance tab, change "xml enable plugin attributes" to "yes".

This fixed our missing data in Tenable.sc .nessus files.

**Comment by rich-diesel** [comment]
We are having the same issue with Nessus 8.7.1

Known issue?

**Comment by rich-diesel** [comment]
> 
> 
> Nessus version 8.6.0 includes bug fix, plugin attributes were no longer included in .nessus files sent to T.sc.
> 
> In Nessus 8.6.0 software, under settings, advanced settings, performance tab, change "xml enable plugin attributes" to "yes".
> 
> This fixed our missing data in Tenable.sc .nessus files.

This worked for us on 8.7.1 - thanks!
