### ISSUE TITLE
Producing unknowns from Nessus files

### ISSUE THREAD

**Issue by treesaregreenish** [Vulnerator/Vulnerator#176]
#### Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [X] I have ensured that I am running the latest release
- [X] The issue is repeatable
- [X] The issue has not already been reported
- [X ] The issue does not fit into one of the suggested categories (Assistance Request, Bug Report, or Feature Request)

#### Description
When running credentialed .nessus files through Vulnerator, it populates the POA&M tab about 44 plugins that have a Raw Severity Value as "unknown".  The same plugins are also listed on the RAR tab with Raw Test Results and Impact as unknown.  I've looked the plugins up in eMASS (using Raw Severity) and ACAS (using Risk Factor), but there doesn't seem to be similarities that are causing the "unknown" output to appear (i.e. similar vulnerabilities, severities, or released dates).  Many of them were informational in ACAS, but some of them were not.  The devices in the scans are all network devices (routers, switches, etc).  If there's any additional details needed, please just let me know!
Many thanks in advance!

#### System Information
 - _**OS:** Win10
 - _**Version:** v6.1.9

#### Additional Context
None I can think of.

#### Attachments

- [ ] Vulnerator Log (required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (optional, _**SANITIZED/REDACTED**_)
- [ ] Vulnerability Files (optional, _**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@treesaregreenish two things:

1. You have one of the best Github names I have read in a very long time.  If it's not the best ever, it's easily top 3
2. Does your issue, by any chance, relate to #173 or #174?

Thank you for submitting this!  I will label it for triage purposes and await your response!

**Comment by treesaregreenish** [comment]
1. Tyvm!  Usually I'm awful at picking names.  :)
2. Yes, it does, sorry I missed those!  The scanner versions used were 8.4.0 and 8.6.0, but not 8.5.x.  I will ask if "xml enable plugin attributes" to "yes" and if we repair plugins after updates (both suggestions from #173).  Hopefully I will get an answer today or tomorrow.

**Comment by treesaregreenish** [comment]
Ok, here's what else I've tried - I have 10 nessus files that I originally processed together.  When I processed them altogether, the Asset Overview shows 10 files, but then lists out duplicate entries for 7 of them on the Test Plan tab.  The duplicates were listed with Scanner version 8.4.0 and 8.6.0, with ones of the duplicates reporting a Placeholder (PH) for the Scanner Version, and then there are a bunch of unknowns on the POAM tab (Raw Severity Value).

When I processed the scan that had the PH duplicate by itself, it returned with one host (correct) and 8.4.0 (also correct), and 0 unknowns on the POAM tab (Raw Severity Value).

When I processed a scan that had duplicates by itself, it returned with one host (correct) and 8.6 (also correct), but had 44 unknowns on the POAM tab (Raw Severity Value).

Definitely looks to be 8.6 related.

We're currently chasing down the ACAS guy to check if "xml enable plugin attributes" is set to "yes" in 8.6 - apparently that's not an option in 8.4.

**Comment by amkuchta** [comment]
@treesaregreenish I am going to go ahead and close this for now, since it appears to be a non-Vulnerator issue.  If that changes, please feel free to re-open it (or let me know and I will re-open).

I'm glad you got to the root of the issue!

**Comment by treesaregreenish** [comment]
@amkuchta I have scans from last night, all run from 8.6 with "xml enable plugin attributes" as "yes", and from the same Security Center.  When I run them through as a batch, something somewhere is causing duplicate entries on the Test Plan tab.  The duplicates have just the IP listed, then Scan Tool, Scanner Version, and Plugin Engine are all reported as Placeholder or PH. 

When I run the files separately, they do not have duplicates.

The severities are populating correctly on the POAM tab, so it's just something wonky on the Test Plan.  Not an earth-shattering issue, but it does appear to be an issue somewhere.  Thanks again, and let me know if I can provide additional info!
