### ISSUE TITLE
Updating and Future Support

### ISSUE THREAD

**Issue by SMoseley44** [Vulnerator/Vulnerator#177]
#### Prerequisites
_Before submitting a new request, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [X] I have ensured that I am running the latest release
- [X] The request has not already been reported

#### Description

I wanted to reach out and see if this project is still supported or updated? I am working on multiple VA and DoD projects that leverage this tool. 

Thank you.

**Comment by amkuchta** [comment]
As a side note, if anyone cares to follow along, the latest code can be found on my fork of the repository, located [here](https://github.com/amkuchta/Vulnerator).  Be sure to check out all of the branches to find the latest commits!

**Comment by SMoseley44** [comment]
@amkuchta Thanks for the reply. I know that supporting items not funded can be a challenge, especially  working in DoD ( Contractor Myself under DHA). I am happy to heat that FTE is being reviewed or authorized. I am not a dev by any  means, but I can provide perspective from this side of the house if you ever need to smoke test an item.
