### ISSUE TITLE
Vulnerator shows error "Unable to process XCCDF file"

### ISSUE THREAD

**Issue by Pradyumna2020** [Vulnerator/Vulnerator#184]
We are running SCC tool 5.2.1 and Vulnerator 6.1.9 version.
We could able to import XCCDF file but we are facing issue while parsing SCC XCCDF file in Vulnerator.  It shows error as "Unable to process XCCDF file", could you let us know the root cause and how to resolve it.

**Comment by amkuchta** [comment]
It looks like DISA changed the format of the XCCDF file a bit - some of the attributes in the file that Vulnerator uses to identify required fields that were lowercase are now uppercase, which is causing the failure.

I'll hop on this as a priority.  Thank you for the bug report, @Pradyumna2020!

**Comment by tsords** [comment]
I came here to mention that I was having problems with this as well.  When running the SCAP 1.2 based benchmarks, regardless of the version of SCC (5.0.2, 5.1 or 5.2.1) it will fail with the message "Unable to process XCCDF file" on a machine that has Internet access, but succeed when it is run on a machine that has no Internet access.

For further information, both machines have similar group policy, are one the same domain, and are 96% STIG compliant (OS, IE, .NET).

Running Windows 10 1903, and Vulnerator 6.1.9

**Comment by Pradyumna2020** [comment]
@tsords Thanks for the update but this is not working.
Do you have any update @amkuchta .

**Comment by CyberSecDef** [comment]
Would it be possible to get a list of the applicable attributes that changed capitalization?  I'd be interested in incorporating XCCDF changes into my own tools, but don't have source scans that are causing issues.  If not, would it be possible to get the XCCDF Schema changes maybe?

**Comment by roottusk** [comment]
Looks like there's some problem in parsing the <VulnDiscussion> parameter from <cd:Description> block , tried removing the text in between for every rule and it worked.Could it be a malformed character or an angular bracket making its way to the VulnDiscussion parameter ?  .We were having trouble for Apache xccdf parsing, the above method worked.
