### ISSUE TITLE
Where is vulnerator.exe file?

### ISSUE THREAD

**Issue by RayMakuch** [Vulnerator/Vulnerator#185]
#### Prerequisites
_Before submitting a new request, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The request has not already been reported

#### Description
_Please provide a brief synopsis of the request or the help needed._

#### System Information
 - _**OS:**_ [e.g. Windows 10]
 - _**Version:**_ [e.g. v6.1.9]

#### Additional Context
_Add any other context about the problem here, if applicable._

#### Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (optional, _**SANITIZED/REDACTED**_)
- [ ] Vulnerability Files (optional, _**SANITIZED AND EMAILED**_)

**Comment by RayMakuch** [comment]
Where is the Vulnerator.exe file.?  Just downloaded zip today, and I do not see it.

**Comment by amkuchta** [comment]
@RayMakuch I apologize for the late response - the *.exe file should be located directly in the root of the ZIP file itself once you decompress it.
