### ISSUE TITLE
Fortify import fails

### ISSUE THREAD

**Issue by deepgray** [Vulnerator/Vulnerator#194]
#### Prerequisites
_Before submitting a new request, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [X] I have ensured that I am running the latest release
- [X] The request has not already been reported

#### Description
_Please provide a brief synopsis of the request or the help needed._

importing a .fpr file from Fortify, the Status field shows "Failed: See Log".

where is the log? I don't see it with the .xlsx file nor do I see it in the Vulnerator directory.

#### System Information
 - _**OS:**_ [e.g. Windows 10]
 - _**Version:**_ [e.g. v6.1.9]

#### Additional Context
_Add any other context about the problem here, if applicable._

#### Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (optional, _**SANITIZED/REDACTED**_)
- [ ] Vulnerability Files (optional, _**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
I finalized the rework of how FPR files are ingested last Friday, and am currently testing this more extensively now.

**Comment by amkuchta** [comment]
Fortify FPR files now parse correctly from v18.2 and 20.x
