### ISSUE TITLE
Does anyone know when the next release of Vulnerator will be available?  V6.1.9 is several years old and I see that v6.2.0 beta has been in development, however, don't see any progress.  Please advise on the status of the Vulnerator project.

### ISSUE THREAD

**Issue by MKStapleton** [Vulnerator/Vulnerator#195]
#### Prerequisites
_Before submitting a new request, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [ ] I have ensured that I am running the latest release
- [ ] The request has not already been reported

#### Description
_Please provide a brief synopsis of the request or the help needed._

#### System Information
 - _**OS:**_ [e.g. Windows 10]
 - _**Version:**_ [e.g. v6.1.9]

#### Additional Context
_Add any other context about the problem here, if applicable._

#### Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (optional, _**SANITIZED/REDACTED**_)
- [ ] Vulnerability Files (optional, _**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@MKStapleton the application *very* recently got put under my team officially, and I started full-time work on it last week.  We are targeting an end of July release of the initial "alpha" build for user acceptance testing.

**Comment by MKStapleton** [comment]
Alex,

Thank you.  I am looking forward to seeing the new version.

Sent from my iPhone - Michael Stapleton 
804-930-6056
