### ISSUE TITLE
SCAP import very slow

### ISSUE THREAD

**Issue by vanerj1996** [Vulnerator/Vulnerator#34]
Importing of XCCDF files into Vulnerator is very slow, and surprisingly consistent just below 30 seconds. (I have nearly 150 XCCDF to import, which makes for very long run times.)

I believe the issue is the attempt to validate Xml Schema before parsing. But my machine is airgapped! So those internet downloads are doomed to fail (timeout). I suspect the consistency is from some timeout. (However that validator, download mechanism, and timeout are deep within the .Net API.)

Several solutions come to mind:
- Turn off validation entirely (brute force)
- A "non-internet connected mode" which doesn't bother to retrieve schema from online. But if connected, would validate. (better)
- Include the schemas at install time (possibly the most secure option. Theoretically, XML schema could have embedded malware!!)

**Comment by vanerj1996** [comment]
Workaround: I added "scap.nist.gov", "checklists.nisc.gov", "cpe.mitre.org" to my hosts file, and resolved them to "127.0.0.1". -- Now the validator "fails fast".

**Comment by amkuchta** [comment]
I will look into adding the schemas for utilization at runtime - I do something similar for the CCI References, so mimicking the behavior shouldn't be difficult.
