### ISSUE TITLE
Add DIACAP IA / RMF Security Controls to "STIG Details & Review" Report

### ISSUE THREAD

**Issue by jae-trinity** [Vulnerator/Vulnerator#37]
- [ ] Add DIACAP IA / RMF Security Controls to "STIG Details & Review" - this would allow the output to be used as an adequate .ckl "human readable" output format.

Thanks for the hard work.

**Comment by amkuchta** [comment]
@jae-trinity thanks for the input!  For future reference, please create a new issue for each request (instead of one running one).  This will allow me to track each request separately (making my life easier!)

**Comment by jae-trinity** [comment]
VIDs are incorrectly labeled as STIG IDs in the STIG Details & Review

**Comment by amkuchta** [comment]
^^ Tracked via #50
