### ISSUE TITLE
Automatically Convert DIACAP IAC(s) to RMF Control(s) when no CCI Reference is Available

### ISSUE THREAD

**Issue by amkuchta** [Vulnerator/Vulnerator#44]
Per the discussion in #43 , a class should be created to automatically convert DIACAP IAC(s) to RMF control(s) when no RMF data is present.  This will greatly reduce the amount of "hand-jamming" that must be completed by the analyst.  A current mapping of IACs to NIST SP 800-53 controls can be found on the RMF Knowledge Service.

**Comment by amkuchta** [comment]
@caday00 is there any reason in particular that you included both Rev3 and Rev4 controls in the sample class provided in #43?  I am thinking of moving ahead using the DIACAP to RMF crosswalk provided by the RMF knowledge service, and it does not include the Rev3 line items.

**Comment by caday00** [comment]
Yes, unfortunately several IC authorizing officials are still using Rev3...

**Comment by amkuchta** [comment]
@caday00 heard - I will work to integrate both, just to be on the safe side.

**Comment by amkuchta** [comment]
@caday00 just a heads up, I am working on implementing this feature now; I am mapping out all of the controls to an XML file that will then be read at run time and used to populate the dictionaries for Rev3/4.  I figure that this will result in less code, and when Rev5 drops, all I have to do is update the XML file, add a new dictionary, and be done.

I am hoping to have this integrated by COB tomorrow - if you'd like, I can send you a copy to test out for me.
