### ISSUE TITLE
POA&M/RAR output no longer includes valuable 'Risk Statement' and 'Recommended Corrective Action' data 

### ISSUE THREAD

**Issue by helms-rj** [Vulnerator/Vulnerator#46]
The last two Vulnerator releases (6.1.1 and now 6.1.2) omit the valuable data provided in version 6.0.2 when parsing XCCDF files and selecting RAR/POA&M output.  Specifically, on the RAR tab, the Risk Statement (5), and Recommended Corrective Action (9) fields that were included in v6.0.2 are gone in v6.1.2.  The Recommended Corrective Action data is vital for remediation work.  Also, in v6.1.2 the Identifier Applicable Security Control (1) field is present, but it does not populate with data.  This data did appear in v6.0.2 as was also valuable.

To demonstrate these differences, I've attached is sample Vulnerator output with TWO Tabs - one for v6.1.2 and one for v6.0.2 in order to fully demonstrate the issue.   Note there are 15 columns of data for v6.0.2 but now only 13  columns of data for v6.1.2.  The missing information is very important, especially the corrective action data. 

Are there plans to re-able these features in upcoming versions of Vulnerator?
[Sample RAR Output Vuln6-1-2 and Vuln6-0-2.xlsx](https://github.com/Vulnerator/Vulnerator/files/442634/Sample.RAR.Output.Vuln6-1-2.and.Vuln6-0-2.xlsx)

**Comment by amkuchta** [comment]
@helms-rj please allow me to answer your comment in two parts:

1. The two columns you referenced were intentionally removed in an attempt to comply with the DoD RMF RAR.  That being said, I will be making a future update to comply with the DoN RAR, which is more verbose while still complying with DoD standards for the sake of reciprocity - if I remember correctly, the DoN Template has the columns you were looking for.
2. As for the Identifier Applicable Security Control not being present, have you gotten a chance to review #43 and #44?

**Comment by amkuchta** [comment]
@helms-rj I had a second thought that is worth mentioning as an interim fix - the information that you are looking for for both STIG and ACAS findings can be found on the "STIG Details" and "ACAS Output" reports, respectively.

**Comment by helms-rj** [comment]
Alex,
Thank you for the reply.   Because  of the way things work at my SPAWAR facility, we  have to rely on Vulnerator to get those details for remediation work.  It's too complicated to explain why, but we are not provided with any other SCAP scan results other than the XCCDF files.  We look forward to a future release that will add those columns back in.

I did not see #43 and #44, but did a quick review.  It appears v6.1.3 will address these issues.

Thank you again for being responsive.  Vulnerator is a great tool!  

Respectfully,
Rebecca

Rebecca Helms
Cyber Operations Lead/ISSE
PEO EIS PMW 240 
SPAWAR Systems Center Atlantic, New Orleans Office
Work: (504) 697-1519 
DSN: 647-1519
Mobile: (504) 782-9503
Email: rebecca.helms2@navy.mil


-----Original Message-----

**Comment by helms-rj** [comment]
Alex,
I was only referring to the STIGs, not ACAS.  I get the ACAS output information.  I  do not get the STIG Details when importing the XCCDF files, no matter what options I select.  The STIG Details & Review tab iscreated, but it is always blank.    Is that only available if importing .ckl files?  

If so, I will have to import XCCDF into STIGViewer, create checklists, and then go back to Vulnerator.  This will be a timely process that is prohibitive.   


Respectfully,
Rebecca

Rebecca Helms
Cyber Operations Lead/ISSE
PEO EIS PMW 240 
SPAWAR Systems Center Atlantic, New Orleans Office
Work: (504) 697-1519 
DSN: 647-1519
Mobile: (504) 782-9503
Email: rebecca.helms2@navy.mil


-----Original Message-----

**Comment by amkuchta** [comment]
@helms-rj I will be implementing an update in the near future that will either create a new tab for SCCDF details or (more than likely) integrate the XCCDF Details into the "STIG Details" tab.

As a side note, I got a chance to really deep-dive the DoN RAR template yesterday - no Recommended Corrective Action or Risk Statement columns :disappointed:

**Comment by helms-rj** [comment]
Alex,
Thank you so much for your responsiveness.  I will wait for updates and leverage whatever new features I can.    I appreciate all the great work you and others have done in providing this tool!

Respectfully,
Rebecca

Rebecca Helms
Cyber Operations Lead/ISSE
PEO EIS PMW 240 
SPAWAR Systems Center Atlantic, New Orleans Office
Work: (504) 697-1519 
DSN: 647-1519
Mobile: (504) 782-9503
Email: rebecca.helms2@navy.mil

-----Original Message-----

**Comment by jae-trinity** [comment]
Recommend not updating the RAR, but providing the STIG "fix text" to the STIG Details & Review.

**Comment by amkuchta** [comment]
Looking at the RAR template, I believe that @jae-trinity is on the right track.  The goal of the reports is to adhere as closely to the provided templates as possible - deviation means additional work for the analyst.

**Comment by helms-rj** [comment]
I agree with that recommendation as it will resolve the issue of not having remediation guidance, yet retain the elements required for the RMF format.

Respectfully,
Rebecca

Rebecca Helms
Cyber Operations Lead/ISSE
PEO EIS PMW 240 
SPAWAR Systems Center Atlantic, New Orleans Office
Work: (504) 697-1519 
DSN: 647-1519
Mobile: (504) 782-9503
Email: rebecca.helms2@navy.mil


-----Original Message-----
