### ISSUE TITLE
Issue with mapping hostname for .nessus files

### ISSUE THREAD

**Issue by mcshea98** [Vulnerator/Vulnerator#51]
When conducting assessments of lab networks or systems, the *.nessus files do not populate the hostname properly.  I believe this is related to the ACAS server not being able to conduct DNS or Reverse DNS lookups. 

When Vulnerator (v6.1.2 and prior) parses *.nessus files, it appears that only the <tag name="host-fqdn"> field maps to the "Hostname" column.  Can you add a rule that if there is no "host-fqdn" to use "netbios-name" or "hostname" tags?

Maybe?:

AcasNessusReader.cs 
(insert near line 202)
`                            case "netbios-name":
                                {
                                    xmlReader.Read();
                                    workingSystem.SetNetbiosName(xmlReader.Value);
                                    break;
                                }`

(insert around line 397)
`                    if (string.IsNullOrWhiteSpace(workingSystem.HostName) && !string.IsNullOrWhiteSpace(workingSystem.NetbiosName))
                    { workingSystem.HostName = workingSystem.NetbiosName }
`

**Comment by amkuchta** [comment]
Incorporating some logic to utilize the NetBIOS name is not difficult (especially since you have done the work for me!). However, I am not familiar with host name tags in ACAS - do you have a *.nessus file that has an example of this?

As a side note, I am working on incorporating some major upgrades for v6.2.0 that will allow the user to manually map IPs back to host names; this should provide a reduction in time spent with manual cleanup efforts.

**Comment by mcshea98** [comment]
I will find one that has data I can release.  Or I will replace the data with false information.

**Comment by mcshea98** [comment]
Here is an example that has the NetBIOS-name tag and a few plugins that report hostname.  I will find the correct syntax for the "hostname" tag.  I have only seen it a few times, so you could probably get by with just host-fqdn and NetBIOS-name.

`<ReportHost name="1.2.3.4"><HostProperties>
<tag name="HOST_END">Thu Aug 27 16:35:36 2015</tag>

...
<tag name="host-ip">1.2.3.4</tag>
<tag name="host-fqdn">hostname.domain.com</tag>
<tag name="smb-login-used">username</tag>
<tag name="netbios-name">HOSTNAME</tag>
<tag name="HOST_START">Thu Feb 30 15:10:32 2016</tag>
</HostProperties>

<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="55472" pluginName="Device Hostname" pluginFamily="General">
<agent>unix</agent>
<description>This plugin reports a device&apos;s hostname collected via SSH or WMI.</description>
<fname>wmi_system_hostname.nbin</fname>
<plugin_modification_date>2015/07/06</plugin_modification_date>
<plugin_name>Device Hostname</plugin_name>
<plugin_publication_date>2011/06/30</plugin_publication_date>
<plugin_type>local</plugin_type>
<risk_factor>None</risk_factor>
<script_version>$Revision: 1.8 $</script_version>
<solution>n/a</solution>
<synopsis>It is possible to determine the remote system hostname.</synopsis>
<plugin_output>
  Hostname : HOSTNAME
</plugin_output>
</ReportItem>

<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="46180" pluginName="Additional DNS Hostnames" pluginFamily="General">
<description>Hostnames different from the current hostname have been collected by miscellaneous plugins.  Different web servers may be hosted on name- based virtual hosts.</description>
<fname>alternate_hostnames.nasl</fname>
<plugin_modification_date>2013/01/21</plugin_modification_date>
<plugin_name>Additional DNS Hostnames</plugin_name>
<plugin_publication_date>2010/04/29</plugin_publication_date>
<plugin_type>remote</plugin_type>
<risk_factor>None</risk_factor>
<script_version>1.10</script_version>
<see_also>http://en.wikipedia.org/wiki/Virtual_hosting</see_also>
<solution>If you want to test them, re-scan using the special vhost syntax, such as :

www.example.com[192.0.32.10]</solution>
<synopsis>Potential virtual hosts have been detected.</synopsis>
<plugin_output>The following hostnames point to the remote host:
  - HOSTNAME
</plugin_output>
</ReportItem>`

Also, I haven't code in C# before, so my recommendations should be considered pseudo code.  Hope this helps.

**Comment by mcshea98** [comment]
Here is an example that has the NetBIOS-name tag and a few plugins that report hostname. I will find the correct syntax for the "hostname" tag. I have only seen it a few times, so you could probably get by with just host-fqdn and NetBIOS-name. Also, I haven't code in C# before, so my recommendations should be considered pseudo code. Hope this helps. 

```
<ReportHost name="1.2.3.4"><HostProperties>
<tag name="HOST_END">Thu Aug 27 16:35:36 2015</tag>

...
<tag name="host-ip">1.2.3.4</tag>
<tag name="host-fqdn">hostname.domain.com</tag>
<tag name="smb-login-used">username</tag>
<tag name="netbios-name">HOSTNAME</tag>
<tag name="HOST_START">Thu Feb 30 15:10:32 2016</tag>
</HostProperties>

<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="55472" pluginName="Device Hostname" pluginFamily="General">
<agent>unix</agent>
<description>This plugin reports a device&apos;s hostname collected via SSH or WMI.</description>
<fname>wmi_system_hostname.nbin</fname>
<plugin_modification_date>2015/07/06</plugin_modification_date>
<plugin_name>Device Hostname</plugin_name>
<plugin_publication_date>2011/06/30</plugin_publication_date>
<plugin_type>local</plugin_type>
<risk_factor>None</risk_factor>
<script_version>$Revision: 1.8 $</script_version>
<solution>n/a</solution>
<synopsis>It is possible to determine the remote system hostname.</synopsis>
<plugin_output>
  Hostname : HOSTNAME
</plugin_output>
</ReportItem>

<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="46180" pluginName="Additional DNS Hostnames" pluginFamily="General">
<description>Hostnames different from the current hostname have been collected by miscellaneous plugins.  Different web servers may be hosted on name- based virtual hosts.</description>
<fname>alternate_hostnames.nasl</fname>
<plugin_modification_date>2013/01/21</plugin_modification_date>
<plugin_name>Additional DNS Hostnames</plugin_name>
<plugin_publication_date>2010/04/29</plugin_publication_date>
<plugin_type>remote</plugin_type>
<risk_factor>None</risk_factor>
<script_version>1.10</script_version>
<see_also>http://en.wikipedia.org/wiki/Virtual_hosting</see_also>
<solution>If you want to test them, re-scan using the special vhost syntax, such as :

www.example.com[192.0.32.10]</solution>
<synopsis>Potential virtual hosts have been detected.</synopsis>
<plugin_output>The following hostnames point to the remote host:
  - HOSTNAME
</plugin_output>
</ReportItem>
```

**Comment by mcshea98** [comment]
Here is an example that has the NetBIOS-name tag and a few plugins that report hostname. I will find the correct syntax for the "hostname" tag. I have only seen it a few times, so you could probably get by with just host-fqdn and NetBIOS-name. Also, I haven't code in C# before, so my recommendations should be considered pseudo code. Hope this helps. 

```xml
<ReportHost name="1.2.3.4"><HostProperties>
<tag name="HOST_END">Thu Feb 30 16:35:36 2016</tag>

...
<tag name="host-ip">1.2.3.4</tag>
<tag name="host-fqdn">hostname.domain.com</tag>
<tag name="smb-login-used">username</tag>
<tag name="netbios-name">HOSTNAME</tag>
<tag name="HOST_START">Thu Feb 30 15:10:32 2016</tag>
</HostProperties>

<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="55472" pluginName="Device Hostname" pluginFamily="General">
<agent>unix</agent>
<description>This plugin reports a device&apos;s hostname collected via SSH or WMI.</description>
<fname>wmi_system_hostname.nbin</fname>
<plugin_modification_date>2015/07/06</plugin_modification_date>
<plugin_name>Device Hostname</plugin_name>
<plugin_publication_date>2011/06/30</plugin_publication_date>
<plugin_type>local</plugin_type>
<risk_factor>None</risk_factor>
<script_version>$Revision: 1.8 $</script_version>
<solution>n/a</solution>
<synopsis>It is possible to determine the remote system hostname.</synopsis>
<plugin_output>
  Hostname : HOSTNAME
</plugin_output>
</ReportItem>

<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="46180" pluginName="Additional DNS Hostnames" pluginFamily="General">
<description>Hostnames different from the current hostname have been collected by miscellaneous plugins.  Different web servers may be hosted on name- based virtual hosts.</description>
<fname>alternate_hostnames.nasl</fname>
<plugin_modification_date>2013/01/21</plugin_modification_date>
<plugin_name>Additional DNS Hostnames</plugin_name>
<plugin_publication_date>2010/04/29</plugin_publication_date>
<plugin_type>remote</plugin_type>
<risk_factor>None</risk_factor>
<script_version>1.10</script_version>
<see_also>http://en.wikipedia.org/wiki/Virtual_hosting</see_also>
<solution>If you want to test them, re-scan using the special vhost syntax, such as :

www.example.com[192.0.32.10]</solution>
<synopsis>Potential virtual hosts have been detected.</synopsis>
<plugin_output>The following hostnames point to the remote host:
  - HOSTNAME
</plugin_output>
</ReportItem>
```
