### ISSUE TITLE
Option to Select STIG Finding Details or Comments for Mitigation/Remediation Text (artf377995)

### ISSUE THREAD

**Issue by Vulnerator** [Vulnerator/Vulnerator#6]
Provide users with the ability to decide whether to use the STIG "Finding Details" or "Comments" field for mitigation/remediation text.

**_Note:_** Migration of issue ```artf377995``` from SoftwareForge

**Comment by cmogletree** [comment]
When we import the STIG checklist the comments are not showing in the POA&M, is this saying I need to upgrade to c6.1.1 to resolve this?

**Comment by amkuchta** [comment]
@cmogletree this is correct - in previous versions of the application, the program was hard-coded to select the mitigation for the POA&M from the "Finding Details" section and to dump the "Comments" into the column of the same name on the RAR.  As of v6.1.1, the end user now has the option to utilize the "Findings Details", "Comments", or both.
