### ISSUE TITLE
Consolidated CKL Files only show the name of the first STIG

### ISSUE THREAD

**Issue by spectreltd** [Vulnerator/Vulnerator#61]
STIG check list that contain more then one STIG only show one STIG name. Example if the CKL has both Win 7 and .Net the output has only the .net STIG show.

The RAR tab has no status column. Not sure if this is intended. For us we need a Status column on this report.  
Thank you

**Comment by amkuchta** [comment]
@spectreltd with regards to the STIG Checklist, what version of the STIG Viewer was used to create the *.ckl file?

As for the RAR, I stuck strictly to the DoN RMF RAR Template, which does not have a status column (it is a RAR of NC controls).  From my understanding, the DoN template is the DoD template with additional columns (meaning the DoD template will not have a "Status" column, either).  If that is the case, I will end up leaving the RAR as-is.

**Comment by spectreltd** [comment]
Hi Alex,
The STIG checklist was created with STIG Viewer 2.3.

On the RAR should only be listed items that are Non Compliant? The report
I'm looking at has all the items on the RAR.
Thank you
Ray

**Comment by Kod1ak** [comment]
Sorry to chime in here, but I'm very excited on where this tool is going and have subscribed to the forum as a result. The guidance I have received is that the RAR is the offline (day to day) running list of open and closed vulnerabilities. The POA&M (ultimately destined for eMASS) is the format used for ONLY those items that remain open. I know that VRAM only verifies items on the eMASS POA&M if the vulnerabilities exceed 90 days. RARs should have all vulnerabilities (Open and closed) to the best of my knowledge which is based off of direct guidance from the AO reps. The POA&M will be where we maintain the open or "Ongoing" findings.

**Comment by amkuchta** [comment]
No need to apologize! The whole point of the comment functionality on issues is to promote conversations!  I will take a look at the RAR Template on the RMFKS tomorrow morning and go from there. The issue is picking a template and rolling with it...

**Comment by amkuchta** [comment]
@spectreltd & @Kod1ak I took a look at the DoD RAR on the RMFKS, and there is no Status column located in it, either.  To go further, it also specifies that it is a "RAR of NC Security Controls".  I am going to update the application to only show "Ongoing" findings in the RAR, but will not be updating the template so as to stick with the DoD standard.  I will also make an update to correct the issue with the CKL files only showing the first STIG name - expect to see v6.1.4 briefly.

**Comment by spectreltd** [comment]
Thank you
