### ISSUE TITLE
Asset Overview CAT counts incorrect

### ISSUE THREAD

**Issue by john-sapienza** [Vulnerator/Vulnerator#67]
It appears that the CAT counts are not correct on the Asset overview tab when compared the ACAS output tab.   Also the total counts are off. I have confirmed this with v614 and v613. Please see attached screen shot.
![image](https://cloud.githubusercontent.com/assets/19436916/19944721/5b81fe14-a113-11e6-8abe-f3acbe87a129.png)

**Comment by amkuchta** [comment]
@john-sapienza I have a perfect correlation on my end; please keep in mind that Vulnerator does not strictly use the ACAS-assigned severity to define severity category.  Instead, the logic is as follows:

- If the plugin has an assigned "DISA STIG Severity" level, this is used as the Raw Risk; you may have a finding that is a "High" in ACAS but has a "DISA STIG Severity" of II, making it a CAT II finding
- If no "DISA STIG Severity" is present, ACAS then uses the following mapping:

| ACAS Severity | Raw Risk Category |
| :---: | :---: |
| Critical | CAT I |
| High | CAT I |
| Medium | CAT II |
| Low | CAT III |
| Informational | CAT IV |

Using the above information, are your mappings still off?

**Comment by john-sapienza** [comment]
Unless i'm totally mis-reading what you are saying,  I think they are still off. The totals in Column J  don't seem to be a sum of F,G,H & I  either. I have attached a sanitized copy of my output file for your review.  Thanks ! 

[rts3.xlsx](https://github.com/Vulnerator/Vulnerator/files/568831/rts3.xlsx)

**Comment by amkuchta** [comment]
@john-sapienza I see what you are saying - I will look into this.

The total counts for your number of findings is correct, as are the CAT II/IV counts - only CAT I/III are off, and both are low... which doesn't make sense, since the total is correct.

Long story short, I am looking into it.

**Comment by amkuchta** [comment]
Figured it out - it is only using the ACAS severity level to calculate the "Asset Overview" numbers.

I have an idea of why this may be happening - I'll test my theory and get back to you.

**Comment by amkuchta** [comment]
@john-sapienza I got a fix worked in - I will commit a change in a little while that resolves this issue.  Thanks for bringing it to my attention!

**Comment by john-sapienza** [comment]
That’s great news and a quick turnaround, Thanks Alex! 

-----Original Message-----
