### ISSUE TITLE
STIG details question

### ISSUE THREAD

**Issue by jojones44** [Vulnerator/Vulnerator#79]
Good Morning,

I have question if you could help me that would be great. I uploaded the files from SCC to Vulerator a created the report. that worked great the only thing is in the STIG details, the solution column is coming up blank. Is there anything I'm doing wrong?

**Comment by amkuchta** [comment]
@jojones44 Within the SCC file, there is no "Fix Text" provided that I can pull to place into the "Solution" column.  My suggestion is that you "Vulnerate" a blank copy of the associated *.ckl file (manual STIG checklist) along with the SCC - place the CKL in first, then the SCC file.  This should pull all of the fix text and associate it back to the appropriate vulnerability, which will then populate into the STIG Details tab.  You will simply have to filter out the findings from the manual checklist  on the tab to see your SCC data.

In future releases, I am hoping to incorporate a "tie-in" to the STIG releases, which will allow me to have access to all of the data on all of the STIGs - unfortunately, I just haven't had time to look into / plan the connection.

Let me know if this helps!
