### ISSUE TITLE
STIG's Missing from POAM Tab

### ISSUE THREAD

**Issue by MKStapleton** [Vulnerator/Vulnerator#80]
I recently noticed that all of the Ongoing and/or Not Reviewed STIG ID's listed in the STIG Detail tab were not listed in the POA&M Tab.  I noticed this in version 6.1.4 and verified the same issue in version 6.1.7.  I verified that the POA&M Tab listed 13 of my Firewall STIG findings, however, the STIG Detail tab listed 24 ongoing Firewall STIG findings.  I validated the 24 open STIG findings listed on the STIG Detail tab against the actual Firewall STIG Checklist and wanted to know why some of them are not getting listed in the POA&M Tab.  I am attaching a spreadsheet showing the STIG ID's that were missing from the POA&M tab.

Can you please investigate why V-14671, V-15432, V-17814, V-17821, V-17822, V-17823, V-28784, V-3008, V-3966, V-3982 and V-5612 did not get listed in the POA&M Tab?

[Firewall STIG ID Deltas.xlsx](https://github.com/Vulnerator/Vulnerator/files/717213/Firewall.STIG.ID.Deltas.xlsx)

**Comment by rkotlarz** [comment]
@MKStapleton In the past I've observed were certain text delimiters caused this same issue. If the checklist contains data in the [Finding details] and [Comments] sections try ingesting the checklist again without any metacharacters by simply erasing the content and typing "sample" in both fields.

**Comment by MKStapleton** [comment]
**@rkotlarz** Why would I delete the data from the [Finding Details] and [Comments] section of the checklist?  I want that data captured in the POA&M, RAR, and STIG Details.  If deleting this data from the [Finding Details] and [Comments] section of the checklist I am trying to process, there is a problem with Vulnerator that needs to be addressed.

**Comment by rkotlarz** [comment]
@MKStapleton The reason I recommended removing the data is to test whether or not any characters, metacharacters to be specific, are causing Vulnerator to fail while parsing the data. Vulnerator is a an awesome tool, but at the core it’s still nothing more than an XML parser that ingests data and exports it in an XML format that’s then compressed. When an application such as STIG viewer allows users to input date and doesn’t sanitize the input (which the STIG viewer doesn’t do) it increases the possibilities that the XML parser (Vulnerator) will have issues reading in the files. I’m not part of the development team, but I would recommend that if you want the issue resolved fast, provide the full title of the STIG (there are 12 different firewall STIGs) and test the STIG that you have with and without raw test data. Alternatively you may want to consider sanitizing the data and e-mailing the raw STIG to the developer for further analysis as it's often very difficult to replicate errors that another user has without providing exact details on how it was caused in the first place.

**Comment by amkuchta** [comment]
@MKStapleton I couldn't have said it better myself.  @rkotlarz chances are there is a character (or characters) that I did not account for during the coding process (I tried to grab everything, but I may have missed something).  What I need from you:

- [ ] A sanitized version of the file (no host name or IP address) - this needs to have the vulnerability data populated so that I can see what is missing
- [ ] Which STIG checks are missing (helps me pinpoint the issue)

Please email these to alex.kuchta@navy.mil - once I have them, I will start troubleshooting / debugging to get to the root of the problem.

**Comment by MKStapleton** [comment]
**@amkuchta** Alex, I have included the sanitized version as requested.  I reran it after sanitizing the checklist and noticed that the counts for STIG ID's now match between the STIG Detail tab and the POA&M tab.  Ran it several times with other checklists and ever the ACAS Scans to see if it would give me the results I was seeing before.  I cannot explain why it works now and can only assume that I will need to process each individual checklist to get accurate results versus doing bulk processing of 10 plus checklists.  

The spreadsheet is the vulnerator output with the POA&M and STIG Details.

Again, I have included the files so you can investigate if you feel that it be needed, otherwise, I guess this issue can be closed.
[Network Firewall STIG V8R19.zip](https://github.com/Vulnerator/Vulnerator/files/720100/Network.Firewall.STIG.V8R19.zip)



[Network Firewall STIG V8R19.xlsx](https://github.com/Vulnerator/Vulnerator/files/720066/Network.Firewall.STIG.V8R19.xlsx)

**Comment by MKStapleton** [comment]
Alex,

It is my understanding that v6.2.0 May be available soon, do you have a tentative date?

Sent from my iPhone - Michael Stapleton 
804-930-6056

**Comment by amkuchta** [comment]
@MKStapleton We are actually pushing to have the application over to our internal IA team for a form of "User Acceptance Testing" at the end of next week, and, barring any major issues, I will be pushing a release a few weeks after that.

**Comment by MKStapleton** [comment]
Awesome, look forward to seeing the new version.

Sent from my iPhone - Michael Stapleton 
804-930-6056
