### ISSUE TITLE
.csv failed to parse. need location of error log to analyze.

### ISSUE THREAD

**Issue by DLCOLE65** [Vulnerator/Vulnerator#81]
User guide doesn't provide location of error log when supplied file fails to process. Where is error log location.

**Comment by amkuchta** [comment]
@DLCOLE65 I have been meaning to update the guide - thank you for the reminder!

The guide can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, with ```%UserName%``` replaced by the user name running the application.  As a side note, this is a hidden folder location, so you may need to adjust some settings to view it.

**Comment by dwanamaker** [comment]
I have the same issue where an ACAS DVL in .csv format fails to parse.  Error log states to "generate a CSV file using the ACAS report template that was packaged with the application," but the only file I see is Vulnerator_v6-1-3_ACAS_CSV_TEMPLATE.xml.

**Comment by amkuchta** [comment]
@dwanamaker, the file that you referenced is the report template for the ACAS CSV that Vulnerator parses - in order for the parse to be successful:

1. Import the above-mentioned file into your ACAS instance
2. Modify the file to filter on IP Address(es), Host Name(s), Aset(s), etc. - *do not remove any columns*
3. Generate and export the CSV created by the report template, then import that file into ACAS.

Hopefully this helps!!

**Comment by dwanamaker** [comment]
Ah, duh, got it thanks.

**Comment by amkuchta** [comment]
@dwanamaker not a problem!  I'm going to close this due to lack of response from the originating poster.

**Comment by CyberSecDef** [comment]
While this is fresh on your mind.....is there a reason we have to use the custom CSV templates?  I believe the actual ACAS scan db has more information available to it and it's basically just an XML file.

-----Original Message-----

**Comment by amkuchta** [comment]
@CyberSecDef I am assuming you are referring to the *.nessus file; is this correct?  If so, I actually encourage the use of raw scan data whenever possible - as you mentioned, it is a far more complete format.  I added the CSV option in for those who may not have access to obtain the raw scan files, but still have the ability to generate reports as a sort of "catch all"

**Comment by CyberSecDef** [comment]
Ah.  That makes sense :) 

-----Original Message-----
