### ISSUE TITLE
Not Running on Win 7 Hardened Image 

### ISSUE THREAD

**Issue by joemarotta** [Vulnerator/Vulnerator#83]
Want to know if anyone has had an issue running Vulnerator on a Windows 7 Hardened (Jedi) Image. Task Manager will show it running in Processes, but the program never opens. Anything we can look for? Logs? 

Thanks

**Comment by amkuchta** [comment]
@joemarottam, the error log can be found at C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt, with %UserName% replaced by the user name running the application. As a side note, this is a hidden folder location, so you may need to adjust some settings to view it.  If you can send it to me, I may be able to do some digging.

**Comment by rkotlarz** [comment]
@joemarottam I have found that if you're running a fully STIG / SRG hardened system that you'll run into issues with HIPS/HIDS frameworks (such a as McAfee) stopping non-pre-authorized software from running. If you suspect this is the case temporarily disable the "On Access Scanner" for testing. Keep in mind that most policies will turn this feature back on within a few minutes so if you plan on using it often I would consider making an exception. I would also check the OS level event logs for events to see if something not directly related is throwing messages that may shed light on the situation.

**Comment by joemarotta** [comment]
![log](https://cloud.githubusercontent.com/assets/25329613/22429160/aa340ea8-e6d7-11e6-8586-d3a44580e956.JPG)

**Comment by rkotlarz** [comment]
@joemarotta Until @amkuchta is able to respond I would verify that both the Vulnerator application files as well as your user account all have permission to read and write data. 

![image](https://cloud.githubusercontent.com/assets/5693638/22429683/6a320272-e6d9-11e6-87a8-7d520710b604.png)

**Comment by joemarotta** [comment]
I think it has something to due with folder redirection on our system. Our files are not stored locally in C:\Users\%UserName%\AppData\Roaming\Vulnerator,  they are stored on a server, example - \\Server\Share\Users\%UserName%\AppData\Roaming\Vulnerator. 

I have verified permissions to the folders with full control. I have tried running as admin and still nothing happens. We can see the process start but the application never opens.

**Comment by amkuchta** [comment]
@joemarotta my initial diagnoses is that the hardened image is blocking the application from executing SQLite - without this, the application cannot run.  I would check the Windows event logs to see if they can provide any insight as to why the DLL would be prevented from running as a next step. 

My bet is that "V-15724" is the check that is blocking the application from running.

**Comment by rkotlarz** [comment]
@joemarotta Definitely look into Alex's comment but if you want to rule out the folder mapping you can enable symbolic linking to remote shares via GPO followed by leveraging the [mklink] comment to the path. For ref. the GPO can be found at [Computer Config], [Admin Templates], [System], [Filesystem], "Selectively allow the evaluation of a symbolic link".

![image](https://cloud.githubusercontent.com/assets/5693638/22431878/19e901dc-e6e1-11e6-885b-2340f5376719.png)

**Comment by rkotlarz** [comment]
@joemarotta I'm not sure what STIG @amkuchta was referring to, but another item you should consider in the Windows 7 STIG, is verifying that any application whitelisting tools in use have allowed the Vulnerator application to execute. 

**Windows 7 Security Technical Implementation Guide, Version: 1, Release: 24,  28 Oct 2016**
Group ID (Vulid):  V-57637
Group Title: WIN00-000018
Rule ID: SV-75119r3_rule
Severity: CAT II
Rule Version (STIG-ID): WIN00-000018
Rule Title: The operating system must employ a deny-all, permit-by-exception policy to allow the execution of authorized software programs.

If you're using an application whitelisting tool such as AppLocker then you may find insight allowing this by leveraging details from the Windows 7 Secure Host Baseline (SHB) Support Disk zip file found under the "Sunset Baselines" link from the following PKI enabled link. 
https://disa.deps.mil/ext/cop/iase/dod-images/

I'd also look into McAfee logs to ensure that the OnAccess scanner isn't blocking it. Log file path:
C:\ProgramData\McAfee\DesktopProtection\AccessProtectionLog.txt

**Comment by aecasarez** [comment]
@joemarotta Have you figured out how to run this version in your environment? I am experiencing the same issues and we also have folder re-direction in place. Checked HIPS, OAS and windows logs with nothing found. My V6 log looks exactly the same.

**Comment by rkotlarz** [comment]
If you're using Microsoft AppLocker, disable it temporarily to see if that's tripping it up.

Also while this shouldn't be the case, I've observed that some applications running over mapped shares fail as a result of UAC prompts not being permitted. Try changing the following value to [1] to see if that's the case.

Group ID (Vulid):  V-36439
Group Title: Local admin accounts filtered token policy enabled on domain systems.
Rule ID: SV-47847r1_rule

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\
LocalAccountTokenFilterPolicy=1

Another test would be to log on locally as an admin circumventing the mapped desktop and see if that makes a difference in the outcome.

**Comment by joemarotta** [comment]
@aecasarez - the only way I have been able to run it is to use a local account on the PC itself. The account we are using is local only and not using folder redirection. It works fine. 

Once we try to use an account with Folder redirection, its a no go...

**Comment by aecasarez** [comment]
@rkotlarz @joemarotta Thanks. So we tested it with a local account and still no joy. A piece of info i didn't provide is that we are running this on a stand-alone system. Meaning there is no access to GitHub. So when we ran it with a local account, the errors were different. V6log errors: "Unable to retrieve GitHbi Vulnerator release listing" "Unable to retrieve GitHib Vulnerator issue listing"

**Comment by amkuchta** [comment]
@aecasarez @rkotlarz @joemarotta the two items mentioned in the log above should not affect the application from starting - they are merely informational items to let the user (or me) know that the "News" lists are not going to populate due to a network issue or absence.  The application will still continue to compile, as the exceptions are handled appropriately.

**Comment by joemarotta** [comment]
@aecasarez - is the local account an admin account or can you run it as admin?

**Comment by rkotlarz** [comment]
@aecasarez Given that I receive a prompt that the digital signature could not be verified you may want to disable the following STIG setting for testing.

![image](https://cloud.githubusercontent.com/assets/5693638/22749218/898796aa-edfa-11e6-8256-e8a2a3d750ba.png)

**Group ID (Vulid):**  V-16008
**Group Title:** UAC - Application Elevations
**Rule ID:** SV-25120r1_rule
**Severity:** CAT II
**Rule Version (STIG-ID):** 3.140
**Rule Title:** UAC - All application are elevated.

**Vulnerability Discussion:**  This check verifies that Windows elevates all applications, not just signed ones.

**Check Content:**  Analyze the system using the Security Configuration and Analysis snap-in. 
Expand the Security Configuration and Analysis tree view. 
Navigate to Local Policies -> Security Options. 

If the value for “User Account Control: Only elevate executables that are signed and validated” is not set to “Disabled”, then this is a finding.

The policy referenced configures the following registry value:

Registry Hive: HKEY_LOCAL_MACHINE 
Registry Path: \Software\Microsoft\Windows\CurrentVersion\Policies\System\

Value Name: ValidateAdminCodeSignatures

Value Type: REG_DWORD
Value: 0

**Fix Text:** Configure the policy value for Computer Configuration -> Windows Settings -> Security Settings -> Local Policies -> Security Options -> “User Account Control: Only elevate executables that are signed and validated” to “Disabled”.

**Comment by amkuchta** [comment]
@aecasarez @rkotlarz FYSA, I am looking into obtaining a digital signature so that I can digitally sign the application on each build - standby for that in the next release

**Comment by jmontanez** [comment]
@amkuchta So the Cert issue isnt really and issue. We have already relaxed the STIG setting. The issue is the roaming profiles. This is our test scenario:

- On one security domain we dont use Roaming profiles and everything works great.
- On the other security domain we use Roaming profiles for general accounts and it doesnt work. Error logs say that it cannot build the DB. 
- When we use another account with no roaming profiles it works just fine. 

We tried to do a symbolic link for using the general "mklink /D Link Target" and that still didnt work. 

Any other suggestions.

**Comment by rkotlarz** [comment]
@jmontanez I've experienced where system hardening for the Named Pipes settings resulted in networked issues with databases. Given that the SQLite application is on a network resource and that the issue subsides when you're not on a roaming profile I'd give these two a shot. 

Group ID (Vulid):  V-3338
Group Title: Anonymous Access to Named Pipes

Group ID (Vulid):  V-6834
Group Title: Anonymous Access to Named Pipes and Shares

**Comment by amkuchta** [comment]
@jmontanez any movement on this?

**Comment by Ciscorm** [comment]
I have a very similar situation on my systems.  Vulnerator will launch fine when users do not have re-directed folders.  I was able to disable the setting "Restrict Anonymous Access to Named Pipes and Shares" from our hardened image, but it did not help.  The appdata folder is created, but the database creations fail.  Specifically in the V6Log when it doesn't work I see "FindingsDatabaseActions.cs : 49 Findings database creation failed."  - the Vulnerator.exe process runs in the background, but no GUI.

**Comment by MichaelM00** [comment]
It sounds like there needs to be a check to see if the necessary files can be created in the user's profile (%appdata%\Roaming\Vulnerator) or maybe conditional check to see if the profile is roaming?

If the file can't be created or it's on a network share, then a fallback location such as %temp% should be used? The redirected folder seems to be the one variable that's causing issue (Other than the program not being signed).

**Comment by CyberSecDef** [comment]
'%temp%' is explicitly blocked here at NSWC DD.

-----Original Message-----

**Comment by jmontanez** [comment]
All of DoD have %Temp% blocked by policy, so that will never work

**Comment by CyberSecDef** [comment]
That in itself is one of the most annoying policies that really accomplishes nothing.

-----Original Message-----

**Comment by Ciscorm** [comment]
It is possible that if in:

FindingsDatabaseActions.cs
(Environment.SpecialFolder.ApplicationData) was instead -> (Environment.SpecialFolder.LocalApplicationData) for the findingsDatabaseFilePath 
The SQLite DB would exist locally instead of on the network (re-directed) location, and it would still be synchronized with the roaming profile in theory.  

There are probably many other factors that I do not know, maybe Vulnerator files required to be co-located.  Getting the SQLite DBs to exist locally somehow may solve this specific issue.

**Comment by MichaelM00** [comment]
Noticed that your using `Environment.SpecialFolder.ApplicationData` to determine the path for the sqlite database.

Would `Environment.SpecialFolder.LocalApplicationData` possibly resolve the issue. Per MSDN

_The directory that serves as a common repository for application-specific data that is used by the current, non-roaming user._

Or is DoD also blocking the local application data folder?

https://msdn.microsoft.com/en-us/library/system.environment.specialfolder.aspx

**Comment by amkuchta** [comment]
@joemarotta @rkotlarz @aecasarez @jmontanez @Ciscorm @CyberSecDef @MichaelM00 moving the location of the Vulnerator file to `Environment.SpecialFolder.LocalApplicationData` wouldn't be too difficult - perhaps I can include some logic to utilize that as a fallback?

**Comment by CyberSecDef** [comment]
Just curious, because I haven't coded in C# in years.  Is it possible to keep everything, including the data files, in the directory that Vulnerator executes from?  Might make things go smoother on hardened systems.

Robert F. Weber, Jr.
Senior Cyber Security Solutions Engineer
BS:IT/SW, CASP, CEH, FQNV, MCITP: EA/SA, CIW, JSE6, DBA, A/Net/Sec+
Office 540-653-9831
Mobile 540-538-7764
robert.weber.ctr@navy.mil<mailto:robert.weber.ctr@navy.mil>
weberjr_robert@bah.com<mailto:weberjr_robert@bah.com>
http://www.boozallen.com/

"The quieter you become, the more you are able to hear."
PS > [string][char[]]("81786568818313866865688113668381317764858813767275"-split'(..)'|?{$_;}|%{33+$_;})-replace" "
________________________________

**Comment by amkuchta** [comment]
@CyberSecDef it absolutely is - how does everyone else feel about moving everything there?  It would also make finding items like the Log, Config, and Database files much easier...  My only concern is that users will accidentally delete something if it is right in front of them (hence the reason I "hid" it in the first place)

**Comment by CyberSecDef** [comment]
I like the idea of having everything self contained in the vulnerator folder.  Maybe just add a  blurb to a readme saying 'dont delete things'

Robert F. Weber, Jr.
Senior Cyber Security Solutions Engineer
BS:IT/SW, CASP, CEH, FQNV, MCITP: EA/SA, CIW, JSE6, DBA, A/Net/Sec+
Office 540-653-9831
Mobile 540-538-7764
robert.weber.ctr@navy.mil<mailto:robert.weber.ctr@navy.mil>
weberjr_robert@bah.com<mailto:weberjr_robert@bah.com>
http://www.boozallen.com/

"The quieter you become, the more you are able to hear."
PS > [string][char[]]("81786568818313866865688113668381317764858813767275"-split'(..)'|?{$_;}|%{33+$_;})-replace" "
________________________________

**Comment by vanerj1996** [comment]
It all depends on where you put the folder. 

If you were to install Vulnerator in "C:\Windows", "Program Files", or "Program Files (x86)" you'd have a STIG problem. 
- Those folders are supposed to be written/modified only by a "Trusted Installer". For all other use (or other users), the files are read-only. 
- In this model, runtime-modifiable files need to go elsewhere. If user specific, then in either a user-specific folder (Environment.SpecialFolder.ApplicationData or LocationApplicationData). And for files that are shared-amongst users, go someplace common (Environment.SpecialFolder.CommonApplicationData).  
- Since Microsoft ghost-wrote the original STIG content, this is seen in the Windows 7 STIG. (See V-1130) And other windows OS STIGs. Ultimately it says stick with the default ACLs and don't relax 'em.

So the loophole to that STIG, seems to me...   install it somewhere else!  There's no STIG saying you have to install software into those folders. So it'd seem "legal" to make a folder called "C:\MySandbox" and put whatever ACLs on it you like.

**Comment by MichaelM00** [comment]
Self contained in the Vulnerator folder! Makes it truly portable and won't alter the system it's running on.. This would be key for anyone acting in an Independent Auditor/SCA type role running vulnerator on the actual system.

**Comment by CyberSecDef** [comment]
ironically...on my RDTE machine I have a folder

c:\sandbox\

where I install all the tools and scripts I use for work.

Robert F. Weber, Jr.
Senior Cyber Security Solutions Engineer
BS:IT/SW, CASP, CEH, FQNV, MCITP: EA/SA, CIW, JSE6, DBA, A/Net/Sec+
Office 540-653-9831
Mobile 540-538-7764
robert.weber.ctr@navy.mil<mailto:robert.weber.ctr@navy.mil>
weberjr_robert@bah.com<mailto:weberjr_robert@bah.com>
http://www.boozallen.com/

"The quieter you become, the more you are able to hear."
PS > [string][char[]]("81786568818313866865688113668381317764858813767275"-split'(..)'|?{$_;}|%{33+$_;})-replace" "
________________________________

**Comment by vanerj1996** [comment]
I suppose I'd ask next about lifecycle. If Vulnerator is "installed" on audit day to wrangle some data, produce reports, and promptly gets deleted. Then the single folder model is the way to go.

But if Vulnerator is installed "long term". Such that is had a "database" of findings/mitigations over time, (months/quarters) etc. Then it should be "installed" in a more typical place, and keep its data in a typical place, etc.

I imagine most of the users fit the former category. And the single folder model is desirable.

**Comment by CyberSecDef** [comment]
How about a choice during install?

Do you want to create a portal app or store db in user folders?


Robert F. Weber, Jr.
Senior Cyber Security Solutions Engineer
BS:IT/SW, CASP, CEH, FQNV, MCITP: EA/SA, CIW, JSE6, DBA, A/Net/Sec+
Office 540-653-9831
Mobile 540-538-7764
robert.weber.ctr@navy.mil<mailto:robert.weber.ctr@navy.mil>
weberjr_robert@bah.com<mailto:weberjr_robert@bah.com>
http://www.boozallen.com/

"The quieter you become, the more you are able to hear."
PS > [string][char[]]("81786568818313866865688113668381317764858813767275"-split'(..)'|?{$_;}|%{33+$_;})-replace" "
________________________________

**Comment by amkuchta** [comment]
@vanerj1996 @rkotlarz @CyberSecDef @MichaelM00 the "lifecycle" wouldn't matter much, as users can adjust where they store their database in-app (there is a setting for it).  The initial creation place would be in the Vulnerator folder, but users would have the ability to modify that at a later time to place the database in a more permanent or shared location.  With regards to the config file, it is separate from the application database, so having it in the Vulnerator launch folder is no big deal - same goes for logs, as they can be dumped literally anywhere.  Finally, most users that I have encountered run Vulnerator out of a folder on their Desktop, My Documents, Downloads, or a custom folder, so STIG shouldn't be an issue.

It sounds to me like the easiest way to adjust this is to move the default location for the log, config, and (initial) database files to the runtime location of the application.

**Comment by Ciscorm** [comment]
@amkuchta (and everyone) just a couple thoughts on the recent comments - placing the Log, Config, and Database files in the runtime folder would work except in VDI scenarios where machines are refreshed.  I think those remaining in the user profile with the  Environment.SpecialFolder.LocalApplicationData  adjustment would be best because those should be synchronized. 

As for placing the files/exe in a non standard location, that would be fine on places where application whitelisting is not required, but STIG does require whitelisting.  In our environment (on the unclass side) applocker would prevent non admin users from running the exe in a non standard folder.

**Comment by amkuchta** [comment]
@Ciscorm I can see the argument for having an option to keep the files in a non-updating location.  Maybe I could have a startup action that prompts users for their preferred location for the referenced files?  Having the config and log files overwrite is not a huge deal - all that is stored in the config file is reporting preferences and theme selections, which are easily replacable, and log files are rolled and over-written at run time, anyway.  And, as stated above, the final location of the database file is customizable in app, though the end location is stored in the config file (again, the user would just have to update the file location if the config file was overwritten).  

I guess the point of that rant was to ask this - do we care if the config files are overwritten in instances you described, given that the database file ("meat" of the application) can be moved elsewhere in-app?

As far as whitelisting goes, I will never dictate where users must place the Vulnerator folder - so long as they place it in the whitelisted location, there should be no issues with where the application's files are written to as long as the user has the necessary ACL settings to write to that location.

**Comment by Ciscorm** [comment]
About whitelisting: thanks for the reminder that we can (obviously) place the folder in a whitelist location. I think I started having tunnel vision on that subject.   

Clarify one thing for me about the config files, are we talking about moving the Log/Config/Database files to the runtime (meaning the Vulnerator_v*) folder instead of the user/AppData?  Or are we still talking about trying to adjust from .ApplicationData to .LocalApplicationData?

**Comment by jmontanez** [comment]
The only STIG requirement is that the EVERYONE group cannot have access to
a folder on the C:\ but Authenticated User is perfect for this.

**Comment by amkuchta** [comment]
@Ciscorm I believe that the way things are leaning, I am going to give users the option to launch the application in either a "contained" or "persistent" state; contained will tell Vulnerator to create relevant files in the "Vulnerator_v*" folder, whereas persistent will indicate that the files should be installed in .ApplicationData

**Comment by Ciscorm** [comment]
@amkuchta That would work.  Thanks for your time and help with this issue! - Cisco

**Comment by amkuchta** [comment]
@joemarotta @rkotlarz @aecasarez @jmontanez @Ciscorm @CyberSecDef @vanerj1996 @MichaelM00 so, I need to add a splash screen in between the initial prompt and the main window, but this GIF gives you an idea of how it will work (click to open it in a larger view):

![portablepersistent](https://cloud.githubusercontent.com/assets/6255186/25864234/b5302278-34bc-11e7-9e5a-705ea6f178cb.gif)

Thoughts?

**Comment by jmontanez** [comment]
NIce, When will it be ready to use?

**Comment by amkuchta** [comment]
@jmontanez honestly, I am not entirely sure yet - it's part of the 6.2.0 release, which will be a hot minute due to the scope of work involved.

You can track the project progress [here](https://github.com/Vulnerator/Vulnerator/projects/2)

**Comment by CyberSecDef** [comment]
Love the background....but the customer base might not :)

-----Original Message-----

**Comment by amkuchta** [comment]
@joemarotta @CyberSecDef @MichaelM00 @rkotlarz I have sent you invites to become "members" of the Vulnerator organization as user reps - you provide consistent feedback, and I need a peanut gallery to bounce ideas off of.

If you wouldn't mind accepting the invitation (you'll have to enable two-factor authentication for your account, which is actually quite easy), that would be great!

**Comment by CyberSecDef** [comment]
Would love to be a member.....unfortunately most of the time I work in GitHub I don't have access to a phone so I can't enable two factor authentication.  :(

-----Original Message-----

**Comment by jmontanez** [comment]
Alex, You can add me

**Comment by amkuchta** [comment]
@joemarotta @CyberSecDef @MichaelM00 @rkotlarz if you are already logged in on a system, your login will be retained - it is only future logins that will require 2FA.

**Comment by amkuchta** [comment]
@jmontanez done!

**Comment by CyberSecDef** [comment]
Roger that.  I'll turn it on as soon as I have access to my phone (the sign up process still requires it)

-----Original Message-----
