### ISSUE TITLE
Provide handling for all finding types and all fields when character count exceeds 32767

### ISSUE THREAD

**Issue by rkotlarz** [Vulnerator/Vulnerator#84]
I'm using Vulnerator V6.1.7 to read in a single checklist containing multiple STIGs / SRGs. 

**Steps to reproduce the error:**
1. Launch Vulnerator application
2. Select [System Package Type], [RMF]
3. Select [NIST SP 800-53 Revision], [Revision 4]
4. Select [Import CKL]
5. Navigate to the path of the "Sanitized-multi-STIG-checklist.ckl" // sent to you via AMRDEC
6. Select [Execute]
7. Upon pop-up entered output test.xlsx

Vulnerator shows status message "Processing complete; Excel report created sucessfully; PDF export not required. Upon launching the test.xlsx file Excel shows the message, "The workbook cannot be created or repaired by Microsoft Excel because it is corrupt."

Reviewing logs held in the [C:\Users\%UserName%\AppData\Roaming\Vulnerator\] path show no errors and recreating these steps above but un-selecting the [STIG details] checkbox allows the file to open successfully.

Given that the issue with Excel is removed once the STIG details are not ingested by Vulnerator I'm leaning towards metacharacters causing the issue, however my tools and knowledge of the Excel XML structure is pretty limited so narrowing down what's throwing this error has been difficult.

Any insight that you can provide is appreciated.

**Comment by CyberSecDef** [comment]
I've see that error pop up when the cell content is HUGE....as in larger than 32000 characters.  I'd bet there is some CKL that has way too much data in its comment field or something.

Robert F. Weber, Jr.
Senior Cyber Security Solutions Engineer
BS:IT/SW, CASP, CEH, FQNV, MCITP: EA/SA, CIW, JSE6, DBA, A/Net/Sec+
Office 540-653-9831
Mobile 540-538-7764
robert.weber.ctr@navy.mil<mailto:robert.weber.ctr@navy.mil>
weberjr_robert@bah.com<mailto:weberjr_robert@bah.com>
http://www.boozallen.com/

"The quieter you become, the more you are able to hear."
PS > [string][char[]]("81786568818313866865688113668381317764858813767275"-split'(..)'|?{$_;}|%{33+$_;})-replace" "
________________________________

**Comment by rkotlarz** [comment]
@CyberSecDef Thanks for the input. I'll see if I can script something to perform a character count on between in each XML tag to look for anything over the 32000 limit.

**Comment by CyberSecDef** [comment]
I believe the official limit from excel is 32768, but i always truncate at 32000 to be safe.


Robert F. Weber, Jr.
Senior Cyber Security Solutions Engineer
BS:IT/SW, CASP, CEH, FQNV, MCITP: EA/SA, CIW, JSE6, DBA, A/Net/Sec+
Office 540-653-9831
Mobile 540-538-7764
robert.weber.ctr@navy.mil<mailto:robert.weber.ctr@navy.mil>
weberjr_robert@bah.com<mailto:weberjr_robert@bah.com>
http://www.boozallen.com/

"The quieter you become, the more you are able to hear."
PS > [string][char[]]("81786568818313866865688113668381317764858813767275"-split'(..)'|?{$_;}|%{33+$_;})-replace" "
________________________________

**Comment by rkotlarz** [comment]
@CyberSecDef You're guess was spot on! After looking at the raw data in the CKL file I found that STIG ID [RHEL-07-020880] contained an exceptional amount of characters and that when attempting to simply copy/paste this data into Excel resulted in data being truncated at the 32767 character limit.

@amkuchta If there's a backlog feature wish list, would you mind adding character limitation validation between XML tags?

Thank you both for your help!

Rick Kotlarz

**Comment by amkuchta** [comment]
@rkotlarz not a problem, as I already do this for ACAS text. I am reopening this issue for tracking purposes (and probably changing the title)

**Comment by amkuchta** [comment]
@rkotlarz what field in the CKL file was giving you issues (e.g. "Check Content", "Fix Text", etc.)

**Comment by rkotlarz** [comment]
I don't recall exactly if it was the "Finding details" or "comments" data entry field but Vulnerator didn't error out. It was Excel that had the issue so you should probably throw a warning if data between tags exceeds the character (includes spaces) count. Also I found a few other Excel specifications that you may want to also consider.

https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

Rick

**Comment by amkuchta** [comment]
@rkotlarz I already have a method for handling extremely large amounts of text (seen [here](https://github.com/Vulnerator/Vulnerator/blob/testing/Model/OpenXmlReportCreator.cs#L2319-L2368)).  I am just trying to figure out when it needs to be used... I could make every cell run through the check, but  I don't want to impact performance too much.  I believe in only using items when absolutely necessary.  Also, I will have to modify it to not be so ACAS-centric.

Thoughts?

**Comment by rkotlarz** [comment]
Perhaps include an option or command line switch to enable that function but leave it disabled by default. Then you could simply have it parse between XML tags and do a character count after the Excel file has been generated but before Vulnerator releases the file lock.

Typically I tell users leveraging the STIG viewer to execute commands listed in the STIG and copy the entire output in the "Finding Details". In some Linux and NFS shares this output can be pretty massive. He seems the issue. 

Alternatively you could skip this, and simply make note of it in a user guide and I'll add a defect to the STIG Viewer backlog but I doubt they'll make a change anytime soon. 

Technically it's not a defect of the STIG Viewer or your tool but would appear that way by anyone who's not aware of Excel's limitation and the poor error message that doesn't provide enough guidance on the real issue.

Rick

**Comment by amkuchta** [comment]
I think that if it causes an issue with the file being created correctly, it should be enabled by default.  I think this is also related to #7 , as I have a feeling that there is some large text that is running through my filter.

I am going to try running everything through the method to handle large files, and I am going to optimize that to handle short strings immediately - that should prevent performance degradation, for the most part.

Standby!

**Comment by vanerj1996** [comment]
> I already have a method for handling extremely large amounts of text (seen here). I am just trying to figure out when it needs to be used

Looking briefly in the ancient vulnerator builds...     I had to protect against oversized entries in "discussion"; and 'escape' special characters in Description,  Manual Fix, Manual Check, Details. 

I mention them together because I had thought about combining them to "Scrub" most of the larger text-fields before exporting to Excel.

**Comment by amkuchta** [comment]
@vanerj1996 I am going to "normalize" the text values in WriteCellValues:

```csharp
cellValue = System.Security.SecurityElement.Escape(cellValue);
```

then pass each of the "normalized" values through the large cell value handler.  I'll pass each item throguh to check its size, and return the original string if it is good-to-go:

```csharp
if (cellValue.Length < 32767)
{ return cellValue }
else
{ /*Write value to text, grab text file name, and return that as the cell value*/ }
```

This will also help to clean up some of the code in other areas.

**Comment by amkuchta** [comment]
@rkotlarz @vanerj1996 ok, so I made a few changes that seem to resolve the issue:

- More fields are now run through `LargeCellValueHandler()`, including "Comments" and "FindingDetails"
- The threshold for character count that determines if the raw string is passed to `WriteCellValue()` has been lowered from 32767 to 32000, which gives some buffer room and also seems to resolve #7 (bonus!)

#99 has the code, if you'd like to take a quick glance (or compile and test it against your files, if possible)
