### ISSUE TITLE
Expecting Fortify POAM to provide all .fpr findings instead of just grouping by Class ID/Categorization. Is there a reasoning for the specific layout of the POA&M and Fortify Details or is this still an early release?

### ISSUE THREAD

**Issue by SPAWAR-NG** [Vulnerator/Vulnerator#87]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [X] I have ensured that I am running the latest release
- [X] The issue is repeatable
- [X] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [ ] Enhancement
- [X] Assistance Request (This is not a bug but I still filled out the bug sections)

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

## Synopsis

```text
Expecting Fortify POAM to provide all .fpr findings instead of just grouping by Class ID/Categorization. Is there a reasoning for the specific layout of the POA&M and Fortify Details or is this still an early release?
```

## Expected Outcome
- [ ] N/A (Non-Bug Issue)

```text
In my .fpr file, I have 147 manual findings. My IA lead is expecting 147 findings in the fortify details(including completed) or at least 147 manual findings in POA&M to reflect the .fpr.
```

## Actual Outcome
- [ ] N/A (Non-Bug Issue)

```text
The Fortify detail is showing 203 findings because it is duplicating because certain findings have more than one STIG ID connected to it. The POA&M only shows 28 findings because it is trying to base the POA&M off of the unique Class IDs (there are duplicate Class IDs based on different analysis Values). 
``` 

## Reproduction Steps
- [ ] N/A (Non-Bug Issue)

```text
I ran Vulnerator using a .fpr file.
```

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@SPAWAR-NG When you executed the parsing process, was "Group Fortify" checked?  If so, that would explain why the POA&M was grouped as you described - try unchecking it, and you should get the same number of findings in the POA&M that you get in the Fortify Details report.  For now, I have the "Details" tabs automatically "ungrouped"; I am looking at creating "per-report" filtering options for v6.2.0, which will allow for more granular control over the application (along with the option to just set filters globally and forget about them).

As a side note, thank you for using the issue template!  How did it work for you? Anything you would improve upon?

**Comment by SPAWAR-NG** [comment]
Thanks Alex! However, the problem is that the report is still providing duplicates based off of multiple STIG IDs for the same finding. Are the per-report filtering options for v6.2.0 going to cover removing duplicate findings? For instance one finding may have multiple STIG IDs such as APP3050 and APP3120 and Vulnerator will treat that one findings as 2 instead of just 1. 

The issue template was great for my specific issue. In my browser the text boxes are not word wrapped so it is a bit hard to read for other viewers. Other than that it seems to be a good fit!

**Comment by amkuchta** [comment]
@SPAWAR-NG The duplicate findings are by design (for now).  My intention for the next iteration is to have the application use the HP Fortify results to generate a partially-complete AS&D STIG - in order to do that, I need to have a one-to-one mapping of Fortify findings to their applicable STIG checks in a "pivotable" manner, which is not something that the current database structure is set up for.  Given that I was on a time-crunch (my management wanted the feature), I ended up breaking the findings out in such a way that they could not be easily recombined on the back end.

v6.2.0 will correct this so that the user will be able to decide whether they want a complete, "pivotable" breakout like I have, or whether they would like to group items such as STIG checks by unique finding.

I hope this answers your question!

**Comment by SPAWAR-NG** [comment]
@amkuchta Thanks a lot that does answer my question. I am eagerly awaiting v6.2.0!
