### ISSUE TITLE
Update View & Refactor in Preparation for v6.2.0

### ISSUE THREAD

**Issue by amkuchta** [Vulnerator/Vulnerator#92]
# Prerequisites
_Before submitting a new issue, please ensure you have completed the following (replace the space in the box with an "x" to denote that it has been completed)_

- [x] I have ensured that I am running the latest release
- [x] The issue is repeatable
- [x] The issue has not already been reported
 
# Category
_Please select a category for the item being created_

- [ ] Bug
- [x] Enhancement
- [ ] Assistance Request

# Description
_Please provide a brief synopsis of the feature request or issue; if the item being created is due to a bug, please complete the "Expected Outcome", "Actual Outcome", and "Reproduction Steps" sections as well, otherwise, check the boxes to show that it doesn't apply_

## Synopsis

_With the impending changes to the application for v6.2.0, the current layout (`TabControl` based) is inefficient and easily cluttered.  Additionally, the XAML for the view is convoluted due to its length, making items difficult to find.  The following changes are to be implemented:_

- Move the base view from `TabControl` oriented to `HamburgerMenu`-based
- Separate the various sub-views into user controls based on functionality (e.g. "RMF", "Continuous Monitoring", "Configuration Management", etc.)
- Refactor the code

## Expected Outcome
- [x] N/A (Non-Bug Issue)

## Actual Outcome
- [x] N/A (Non-Bug Issue)

## Reproduction Steps
- [x] N/A (Non-Bug Issue)

# Attachments
_Please provide any relevant attachments, as you see fit (e.g. screenshots); if supplying vulnerability data (e.g. CKL/Nessus files or reports), please ensure that they are sanitized of IP addresses and host names and **email** them to alex.kuchta@navy.mil - **DO NOT POST VULNERABILITY FILES HERE**_

- [ ] Vulnerator Log (Required for bugs) - this can be found at ```C:\Users\%UserName%\AppData\Roaming\Vulnerator\V6Log.txt```, where ```%UserName%``` is the user profile used to run the application
- [ ] Screenshots (Optional)
- [ ] Vulnerability Files (_**SANITIZED AND EMAILED**_)

**Comment by amkuchta** [comment]
@Vulnerator/user-reps I'm working on rewiring some of the logic that I wrote to accommodate new features, and I need some input:

Currently (version <= 6.1.9), if a CKL file does not have an IP address or Host Name provided, the application does nothing to verify file integrity - it simply marks the data as "Host Name / IP Address not provided" and moves on.

Looking forward, incorporating new features such has #30 (vulnerability tracking), data integrity is a must.  I have set the application up to verify that a system identifier is present in the file and to annotate accordingly on file ingestion (see screenshot), but do you think that it would be worthwhile to have the application fail to parse if the data is not present, returning a status along the lines of "Ignored; No Host Name or IP"?  Or would this be a nuisance?

Screen shot:

![verifiedidentifierimage](https://cloud.githubusercontent.com/assets/6255186/26737501/6a242006-4798-11e7-9d49-2f21a4e4ed5a.jpg)

**Comment by vanerj1996** [comment]
My team does this **all the time** to me. When doing a so-called "manual scan" they forget to include IP, host, and MAC address. And other fun variations, like right host-name, and wrong-IP.

I don't figure it out until after running Vulnerator, and seeing strange things on the system summary. A machine will show up twice, a machine will have FAR more findings than its siblings, etc. 

On the one hand: Anything Vulnerator can do to identify that operator-error is welcome. On the other hand, I'll still have to run Vulnerator multiple times (run once, identify the bad CKL, fix the CKL, run Vulnerator again). So it makes no difference in my scenario currently.

But in a future scenario, for data integrity: yeah my vote is to identify/drop/report bad data.

**Comment by brjones3** [comment]
I agree with vanerj1996.  Sometimes I fix the RAR for missing hostnames, if that's easier.  I would rather not have Vulnerator drop .ckl files, unless there is an option to keep current behavior.

**Comment by amkuchta** [comment]
@vanerj1996 @brjones3 I think that's where having the identifiers shown above comes into play - you can quickly hop into the file, make a change, save it, then "Vulnerate", all without making any changes in Vulnerator prior to clicking the "Execute Ingestion" button (you don't even need to delete the file from the list, as all that is included in the list is a reference to the file path.  Any changes made prior to execution would be in effect once parsing begins).  In theory, you still only Vulnerate once, it just requires a bit more work before actual processing begins, which saves a ton of work on the back side.

**Comment by amkuchta** [comment]
@Vulnerator/user-reps another option - instead of dropping the files, read the host name / MAC / IP(s) to text fields that are then editable in-app.  The user can then manually verify the information, adjust on the fly, and execute when ready - the application would pass the fields as variables and make magic happen on the back end.

**Comment by CyberSecDef** [comment]
The problem with this is if the resulting POAM/RAR doesn't match the source files (ckls, nesses, etc)...then ech II might kick back the package because of that mismatch.

-----Original Message-----

**Comment by CyberSecDef** [comment]
I definitely wouldn't just drop the file.  And failing to parse could be a nuisance.  I think showing it but flagging it as bad would probably work out better.

-----Original Message-----

**Comment by amkuchta** [comment]
@CyberSecDef wouldn't you have to go back in and update the raw file after updating the POA&M anyway? Otherwise, you'd update the reports to have the correct info and still have that mismatch.

Also, because I'm ingesting and storing data for Vulnerability Tracking, I'm building in the ability to generate CKL files within Vulnerator. Users will be able to export the corrected data, eliminating mismatches.  My goal is to be able to build a fully traceable package from start to finish in-app. I just finished finalizing the ability to import the entire STIG compilation release into the database today, which gets me halfway there. This will also allow users the ability to do delta analysis in-app as new releases are generated each quarter. Simply upload the new release, and Vulnerator flags findings requiring attention.

**Comment by CyberSecDef** [comment]
I meant that if the POAM/RAR is updated (after the fact or within Vulnerator) to show say host1234 and the ckl says hostname.....that mismatch would cause problems with ech II.  If vulnerator can re-generate the CKLs after the fact, that would solve the problem perfectly.

I really like the idea of handling the package from start to finish.  I can't wait to try that out.

-----Original Message-----

**Comment by 46-Michael** [comment]
@amkuchta , from the viewpoint of the 46th cyber security test squadron, having Vulnerator fail/drop CKLs due to missing hostname/IP addresses/identifiers would be particularly problematic (Worst case, someone may not notice a single checklist failing in larger boundaries). Keep in mind, our use case is slightly different than most. We simply use Vulnerator to generator POA&Ms for a couple hundred programs and the management after that is up to the programs.

If the feature is desired by the community, then some method of disabling or bypassing this check would be appreciated.

**Comment by amkuchta** [comment]
@vanerj1996 @CyberSecDef @46-Michael @brjones3  adding in a toggle to allow users to decide whether or not to use the "drop" feature is definitely doable.  I could also have the application push the data provided in the above mentioned text fields (see screen grab) back to the raw CKL - this would eliminate mismatches.
